// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: Blobs.proto

//go:build protoopaque

package contester_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blob_CompressionInfo_CompressionType int32

const (
	Blob_CompressionInfo_METHOD_NONE Blob_CompressionInfo_CompressionType = 0
	Blob_CompressionInfo_METHOD_ZLIB Blob_CompressionInfo_CompressionType = 1
)

// Enum value maps for Blob_CompressionInfo_CompressionType.
var (
	Blob_CompressionInfo_CompressionType_name = map[int32]string{
		0: "METHOD_NONE",
		1: "METHOD_ZLIB",
	}
	Blob_CompressionInfo_CompressionType_value = map[string]int32{
		"METHOD_NONE": 0,
		"METHOD_ZLIB": 1,
	}
)

func (x Blob_CompressionInfo_CompressionType) Enum() *Blob_CompressionInfo_CompressionType {
	p := new(Blob_CompressionInfo_CompressionType)
	*p = x
	return p
}

func (x Blob_CompressionInfo_CompressionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Blob_CompressionInfo_CompressionType) Descriptor() protoreflect.EnumDescriptor {
	return file_Blobs_proto_enumTypes[0].Descriptor()
}

func (Blob_CompressionInfo_CompressionType) Type() protoreflect.EnumType {
	return &file_Blobs_proto_enumTypes[0]
}

func (x Blob_CompressionInfo_CompressionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Blob struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Compression *Blob_CompressionInfo  `protobuf:"bytes,2,opt,name=compression"`
	xxx_hidden_Sha1        []byte                 `protobuf:"bytes,3,opt,name=sha1"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_Blobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_Blobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Blob) GetCompression() *Blob_CompressionInfo {
	if x != nil {
		return x.xxx_hidden_Compression
	}
	return nil
}

func (x *Blob) GetSha1() []byte {
	if x != nil {
		return x.xxx_hidden_Sha1
	}
	return nil
}

func (x *Blob) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *Blob) SetCompression(v *Blob_CompressionInfo) {
	x.xxx_hidden_Compression = v
}

func (x *Blob) SetSha1(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Sha1 = v
}

func (x *Blob) HasCompression() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Compression != nil
}

func (x *Blob) ClearCompression() {
	x.xxx_hidden_Compression = nil
}

type Blob_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data        []byte
	Compression *Blob_CompressionInfo
	Sha1        []byte
}

func (b0 Blob_builder) Build() *Blob {
	m0 := &Blob{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Compression = b.Compression
	x.xxx_hidden_Sha1 = b.Sha1
	return m0
}

type Module struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,3,opt,name=name"`
	xxx_hidden_Data *Blob                  `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_Type string                 `protobuf:"bytes,1,opt,name=type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_Blobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_Blobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Module) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Module) GetData() *Blob {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Module) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *Module) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Module) SetData(v *Blob) {
	x.xxx_hidden_Data = v
}

func (x *Module) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *Module) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *Module) ClearData() {
	x.xxx_hidden_Data = nil
}

type Module_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
	Data *Blob
	Type string
}

func (b0 Module_builder) Build() *Module {
	m0 := &Module{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Type = b.Type
	return m0
}

type FileBlob struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Data *Blob                  `protobuf:"bytes,2,opt,name=data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileBlob) Reset() {
	*x = FileBlob{}
	mi := &file_Blobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBlob) ProtoMessage() {}

func (x *FileBlob) ProtoReflect() protoreflect.Message {
	mi := &file_Blobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileBlob) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *FileBlob) GetData() *Blob {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *FileBlob) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *FileBlob) SetData(v *Blob) {
	x.xxx_hidden_Data = v
}

func (x *FileBlob) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *FileBlob) ClearData() {
	x.xxx_hidden_Data = nil
}

type FileBlob_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
	Data *Blob
}

func (b0 FileBlob_builder) Build() *FileBlob {
	m0 := &FileBlob{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Data = b.Data
	return m0
}

type Blob_CompressionInfo struct {
	state                   protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_Method       Blob_CompressionInfo_CompressionType `protobuf:"varint,1,opt,name=method,enum=contester.proto.Blob_CompressionInfo_CompressionType"`
	xxx_hidden_OriginalSize uint32                               `protobuf:"varint,2,opt,name=original_size,json=originalSize"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Blob_CompressionInfo) Reset() {
	*x = Blob_CompressionInfo{}
	mi := &file_Blobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob_CompressionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob_CompressionInfo) ProtoMessage() {}

func (x *Blob_CompressionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Blobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Blob_CompressionInfo) GetMethod() Blob_CompressionInfo_CompressionType {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return Blob_CompressionInfo_METHOD_NONE
}

func (x *Blob_CompressionInfo) GetOriginalSize() uint32 {
	if x != nil {
		return x.xxx_hidden_OriginalSize
	}
	return 0
}

func (x *Blob_CompressionInfo) SetMethod(v Blob_CompressionInfo_CompressionType) {
	x.xxx_hidden_Method = v
}

func (x *Blob_CompressionInfo) SetOriginalSize(v uint32) {
	x.xxx_hidden_OriginalSize = v
}

type Blob_CompressionInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Method       Blob_CompressionInfo_CompressionType
	OriginalSize uint32
}

func (b0 Blob_CompressionInfo_builder) Build() *Blob_CompressionInfo {
	m0 := &Blob_CompressionInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_OriginalSize = b.OriginalSize
	return m0
}

var File_Blobs_proto protoreflect.FileDescriptor

const file_Blobs_proto_rawDesc = "" +
	"\n" +
	"\vBlobs.proto\x12\x0fcontester.proto\x1a!google/protobuf/go_features.proto\"\xb4\x02\n" +
	"\x04Blob\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12G\n" +
	"\vcompression\x18\x02 \x01(\v2%.contester.proto.Blob.CompressionInfoR\vcompression\x12\x12\n" +
	"\x04sha1\x18\x03 \x01(\fR\x04sha1\x1a\xba\x01\n" +
	"\x0fCompressionInfo\x12M\n" +
	"\x06method\x18\x01 \x01(\x0e25.contester.proto.Blob.CompressionInfo.CompressionTypeR\x06method\x12#\n" +
	"\roriginal_size\x18\x02 \x01(\rR\foriginalSize\"3\n" +
	"\x0fCompressionType\x12\x0f\n" +
	"\vMETHOD_NONE\x10\x00\x12\x0f\n" +
	"\vMETHOD_ZLIB\x10\x01\"[\n" +
	"\x06Module\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.contester.proto.BlobR\x04data\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"I\n" +
	"\bFileBlob\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.contester.proto.BlobR\x04dataB[\n" +
	"\x1corg.stingray.contester.protoZ+github.com/contester/runlib/contester_proto\x92\x03\r\xd2>\x02\x10\x02\b\x02\x10\x01 \x020\x01b\beditionsp\xe8\a"

var file_Blobs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Blobs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Blobs_proto_goTypes = []any{
	(Blob_CompressionInfo_CompressionType)(0), // 0: contester.proto.Blob.CompressionInfo.CompressionType
	(*Blob)(nil),                 // 1: contester.proto.Blob
	(*Module)(nil),               // 2: contester.proto.Module
	(*FileBlob)(nil),             // 3: contester.proto.FileBlob
	(*Blob_CompressionInfo)(nil), // 4: contester.proto.Blob.CompressionInfo
}
var file_Blobs_proto_depIdxs = []int32{
	4, // 0: contester.proto.Blob.compression:type_name -> contester.proto.Blob.CompressionInfo
	1, // 1: contester.proto.Module.data:type_name -> contester.proto.Blob
	1, // 2: contester.proto.FileBlob.data:type_name -> contester.proto.Blob
	0, // 3: contester.proto.Blob.CompressionInfo.method:type_name -> contester.proto.Blob.CompressionInfo.CompressionType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Blobs_proto_init() }
func file_Blobs_proto_init() {
	if File_Blobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Blobs_proto_rawDesc), len(file_Blobs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Blobs_proto_goTypes,
		DependencyIndexes: file_Blobs_proto_depIdxs,
		EnumInfos:         file_Blobs_proto_enumTypes,
		MessageInfos:      file_Blobs_proto_msgTypes,
	}.Build()
	File_Blobs_proto = out.File
	file_Blobs_proto_goTypes = nil
	file_Blobs_proto_depIdxs = nil
}
