// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: Contester.proto

package contester_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compilation_Code int32

const (
	Compilation_Unknown Compilation_Code = 0
	Compilation_Success Compilation_Code = 1
	Compilation_Failure Compilation_Code = 2
)

// Enum value maps for Compilation_Code.
var (
	Compilation_Code_name = map[int32]string{
		0: "Unknown",
		1: "Success",
		2: "Failure",
	}
	Compilation_Code_value = map[string]int32{
		"Unknown": 0,
		"Success": 1,
		"Failure": 2,
	}
)

func (x Compilation_Code) Enum() *Compilation_Code {
	p := new(Compilation_Code)
	*p = x
	return p
}

func (x Compilation_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compilation_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_Contester_proto_enumTypes[0].Descriptor()
}

func (Compilation_Code) Type() protoreflect.EnumType {
	return &file_Contester_proto_enumTypes[0]
}

func (x Compilation_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compilation_Code.Descriptor instead.
func (Compilation_Code) EnumDescriptor() ([]byte, []int) {
	return file_Contester_proto_rawDescGZIP(), []int{0, 0}
}

type Compilation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Failure     bool                  `protobuf:"varint,1,opt,name=failure,proto3" json:"failure,omitempty"`
	ResultSteps []*Compilation_Result `protobuf:"bytes,2,rep,name=result_steps,json=resultSteps,proto3" json:"result_steps,omitempty"`
}

func (x *Compilation) Reset() {
	*x = Compilation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Contester_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Compilation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compilation) ProtoMessage() {}

func (x *Compilation) ProtoReflect() protoreflect.Message {
	mi := &file_Contester_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compilation.ProtoReflect.Descriptor instead.
func (*Compilation) Descriptor() ([]byte, []int) {
	return file_Contester_proto_rawDescGZIP(), []int{0}
}

func (x *Compilation) GetFailure() bool {
	if x != nil {
		return x.Failure
	}
	return false
}

func (x *Compilation) GetResultSteps() []*Compilation_Result {
	if x != nil {
		return x.ResultSteps
	}
	return nil
}

type Compilation_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StepName  string          `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Execution *LocalExecution `protobuf:"bytes,2,opt,name=execution,proto3" json:"execution,omitempty"`
	Failure   bool            `protobuf:"varint,3,opt,name=failure,proto3" json:"failure,omitempty"`
}

func (x *Compilation_Result) Reset() {
	*x = Compilation_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Contester_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Compilation_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compilation_Result) ProtoMessage() {}

func (x *Compilation_Result) ProtoReflect() protoreflect.Message {
	mi := &file_Contester_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compilation_Result.ProtoReflect.Descriptor instead.
func (*Compilation_Result) Descriptor() ([]byte, []int) {
	return file_Contester_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Compilation_Result) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *Compilation_Result) GetExecution() *LocalExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *Compilation_Result) GetFailure() bool {
	if x != nil {
		return x.Failure
	}
	return false
}

var File_Contester_proto protoreflect.FileDescriptor

var file_Contester_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9e, 0x02, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x65, 0x70,
	0x73, 0x1a, 0x7e, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x74, 0x65, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x74, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x22, 0x2d, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x02,
	0x42, 0x4b, 0x0a, 0x1c, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x72, 0x61, 0x79,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6e, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Contester_proto_rawDescOnce sync.Once
	file_Contester_proto_rawDescData = file_Contester_proto_rawDesc
)

func file_Contester_proto_rawDescGZIP() []byte {
	file_Contester_proto_rawDescOnce.Do(func() {
		file_Contester_proto_rawDescData = protoimpl.X.CompressGZIP(file_Contester_proto_rawDescData)
	})
	return file_Contester_proto_rawDescData
}

var file_Contester_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Contester_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Contester_proto_goTypes = []interface{}{
	(Compilation_Code)(0),      // 0: contester.proto.Compilation.Code
	(*Compilation)(nil),        // 1: contester.proto.Compilation
	(*Compilation_Result)(nil), // 2: contester.proto.Compilation.Result
	(*LocalExecution)(nil),     // 3: contester.proto.LocalExecution
}
var file_Contester_proto_depIdxs = []int32{
	2, // 0: contester.proto.Compilation.result_steps:type_name -> contester.proto.Compilation.Result
	3, // 1: contester.proto.Compilation.Result.execution:type_name -> contester.proto.LocalExecution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Contester_proto_init() }
func file_Contester_proto_init() {
	if File_Contester_proto != nil {
		return
	}
	file_Local_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Contester_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Compilation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Contester_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Compilation_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Contester_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Contester_proto_goTypes,
		DependencyIndexes: file_Contester_proto_depIdxs,
		EnumInfos:         file_Contester_proto_enumTypes,
		MessageInfos:      file_Contester_proto_msgTypes,
	}.Build()
	File_Contester_proto = out.File
	file_Contester_proto_rawDesc = nil
	file_Contester_proto_goTypes = nil
	file_Contester_proto_depIdxs = nil
}
