// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: Contester.proto

//go:build protoopaque

package contester_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Compilation_Code int32

const (
	Compilation_Unknown Compilation_Code = 0
	Compilation_Success Compilation_Code = 1
	Compilation_Failure Compilation_Code = 2
)

// Enum value maps for Compilation_Code.
var (
	Compilation_Code_name = map[int32]string{
		0: "Unknown",
		1: "Success",
		2: "Failure",
	}
	Compilation_Code_value = map[string]int32{
		"Unknown": 0,
		"Success": 1,
		"Failure": 2,
	}
)

func (x Compilation_Code) Enum() *Compilation_Code {
	p := new(Compilation_Code)
	*p = x
	return p
}

func (x Compilation_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compilation_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_Contester_proto_enumTypes[0].Descriptor()
}

func (Compilation_Code) Type() protoreflect.EnumType {
	return &file_Contester_proto_enumTypes[0]
}

func (x Compilation_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Compilation struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Failure     bool                   `protobuf:"varint,1,opt,name=failure"`
	xxx_hidden_ResultSteps *[]*Compilation_Result `protobuf:"bytes,2,rep,name=result_steps,json=resultSteps"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Compilation) Reset() {
	*x = Compilation{}
	mi := &file_Contester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compilation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compilation) ProtoMessage() {}

func (x *Compilation) ProtoReflect() protoreflect.Message {
	mi := &file_Contester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Compilation) GetFailure() bool {
	if x != nil {
		return x.xxx_hidden_Failure
	}
	return false
}

func (x *Compilation) GetResultSteps() []*Compilation_Result {
	if x != nil {
		if x.xxx_hidden_ResultSteps != nil {
			return *x.xxx_hidden_ResultSteps
		}
	}
	return nil
}

func (x *Compilation) SetFailure(v bool) {
	x.xxx_hidden_Failure = v
}

func (x *Compilation) SetResultSteps(v []*Compilation_Result) {
	x.xxx_hidden_ResultSteps = &v
}

type Compilation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Failure     bool
	ResultSteps []*Compilation_Result
}

func (b0 Compilation_builder) Build() *Compilation {
	m0 := &Compilation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Failure = b.Failure
	x.xxx_hidden_ResultSteps = &b.ResultSteps
	return m0
}

type Compilation_Result struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StepName  string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName"`
	xxx_hidden_Execution *LocalExecution        `protobuf:"bytes,2,opt,name=execution"`
	xxx_hidden_Failure   bool                   `protobuf:"varint,3,opt,name=failure"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Compilation_Result) Reset() {
	*x = Compilation_Result{}
	mi := &file_Contester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compilation_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compilation_Result) ProtoMessage() {}

func (x *Compilation_Result) ProtoReflect() protoreflect.Message {
	mi := &file_Contester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Compilation_Result) GetStepName() string {
	if x != nil {
		return x.xxx_hidden_StepName
	}
	return ""
}

func (x *Compilation_Result) GetExecution() *LocalExecution {
	if x != nil {
		return x.xxx_hidden_Execution
	}
	return nil
}

func (x *Compilation_Result) GetFailure() bool {
	if x != nil {
		return x.xxx_hidden_Failure
	}
	return false
}

func (x *Compilation_Result) SetStepName(v string) {
	x.xxx_hidden_StepName = v
}

func (x *Compilation_Result) SetExecution(v *LocalExecution) {
	x.xxx_hidden_Execution = v
}

func (x *Compilation_Result) SetFailure(v bool) {
	x.xxx_hidden_Failure = v
}

func (x *Compilation_Result) HasExecution() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Execution != nil
}

func (x *Compilation_Result) ClearExecution() {
	x.xxx_hidden_Execution = nil
}

type Compilation_Result_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StepName  string
	Execution *LocalExecution
	Failure   bool
}

func (b0 Compilation_Result_builder) Build() *Compilation_Result {
	m0 := &Compilation_Result{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StepName = b.StepName
	x.xxx_hidden_Execution = b.Execution
	x.xxx_hidden_Failure = b.Failure
	return m0
}

var File_Contester_proto protoreflect.FileDescriptor

const file_Contester_proto_rawDesc = "" +
	"\n" +
	"\x0fContester.proto\x12\x0fcontester.proto\x1a!google/protobuf/go_features.proto\x1a\vLocal.proto\"\x9e\x02\n" +
	"\vCompilation\x12\x18\n" +
	"\afailure\x18\x01 \x01(\bR\afailure\x12F\n" +
	"\fresult_steps\x18\x02 \x03(\v2#.contester.proto.Compilation.ResultR\vresultSteps\x1a~\n" +
	"\x06Result\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12=\n" +
	"\texecution\x18\x02 \x01(\v2\x1f.contester.proto.LocalExecutionR\texecution\x12\x18\n" +
	"\afailure\x18\x03 \x01(\bR\afailure\"-\n" +
	"\x04Code\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\v\n" +
	"\aFailure\x10\x02B[\n" +
	"\x1corg.stingray.contester.protoZ+github.com/contester/runlib/contester_proto\x92\x03\r\xd2>\x02\x10\x02\b\x02\x10\x01 \x020\x01b\beditionsp\xe8\a"

var file_Contester_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Contester_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Contester_proto_goTypes = []any{
	(Compilation_Code)(0),      // 0: contester.proto.Compilation.Code
	(*Compilation)(nil),        // 1: contester.proto.Compilation
	(*Compilation_Result)(nil), // 2: contester.proto.Compilation.Result
	(*LocalExecution)(nil),     // 3: contester.proto.LocalExecution
}
var file_Contester_proto_depIdxs = []int32{
	2, // 0: contester.proto.Compilation.result_steps:type_name -> contester.proto.Compilation.Result
	3, // 1: contester.proto.Compilation.Result.execution:type_name -> contester.proto.LocalExecution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Contester_proto_init() }
func file_Contester_proto_init() {
	if File_Contester_proto != nil {
		return
	}
	file_Local_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Contester_proto_rawDesc), len(file_Contester_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Contester_proto_goTypes,
		DependencyIndexes: file_Contester_proto_depIdxs,
		EnumInfos:         file_Contester_proto_enumTypes,
		MessageInfos:      file_Contester_proto_msgTypes,
	}.Build()
	File_Contester_proto = out.File
	file_Contester_proto_goTypes = nil
	file_Contester_proto_depIdxs = nil
}
