// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Execution.proto

package contester_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RedirectParameters struct {
	Filename                 string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Memory                   bool     `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Buffer                   *Blob    `protobuf:"bytes,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	RemoteFilename           string   `protobuf:"bytes,4,opt,name=remote_filename,json=remoteFilename,proto3" json:"remote_filename,omitempty"`
	RemoteAuthorizationToken string   `protobuf:"bytes,5,opt,name=remote_authorization_token,json=remoteAuthorizationToken,proto3" json:"remote_authorization_token,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *RedirectParameters) Reset()         { *m = RedirectParameters{} }
func (m *RedirectParameters) String() string { return proto.CompactTextString(m) }
func (*RedirectParameters) ProtoMessage()    {}
func (*RedirectParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_Execution_2061505c8af4a99d, []int{0}
}
func (m *RedirectParameters) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedirectParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedirectParameters.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RedirectParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectParameters.Merge(dst, src)
}
func (m *RedirectParameters) XXX_Size() int {
	return m.Size()
}
func (m *RedirectParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectParameters.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectParameters proto.InternalMessageInfo

func (m *RedirectParameters) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *RedirectParameters) GetMemory() bool {
	if m != nil {
		return m.Memory
	}
	return false
}

func (m *RedirectParameters) GetBuffer() *Blob {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *RedirectParameters) GetRemoteFilename() string {
	if m != nil {
		return m.RemoteFilename
	}
	return ""
}

func (m *RedirectParameters) GetRemoteAuthorizationToken() string {
	if m != nil {
		return m.RemoteAuthorizationToken
	}
	return ""
}

type ExecutionResultFlags struct {
	Killed                 bool     `protobuf:"varint,1,opt,name=killed,proto3" json:"killed,omitempty"`
	TimeLimitHit           bool     `protobuf:"varint,2,opt,name=time_limit_hit,json=timeLimitHit,proto3" json:"time_limit_hit,omitempty"`
	MemoryLimitHit         bool     `protobuf:"varint,3,opt,name=memory_limit_hit,json=memoryLimitHit,proto3" json:"memory_limit_hit,omitempty"`
	Inactive               bool     `protobuf:"varint,4,opt,name=inactive,proto3" json:"inactive,omitempty"`
	StdoutOverflow         bool     `protobuf:"varint,6,opt,name=stdout_overflow,json=stdoutOverflow,proto3" json:"stdout_overflow,omitempty"`
	StderrOverflow         bool     `protobuf:"varint,7,opt,name=stderr_overflow,json=stderrOverflow,proto3" json:"stderr_overflow,omitempty"`
	StdpipeTimeout         bool     `protobuf:"varint,8,opt,name=stdpipe_timeout,json=stdpipeTimeout,proto3" json:"stdpipe_timeout,omitempty"`
	TimeLimitHitPost       bool     `protobuf:"varint,9,opt,name=time_limit_hit_post,json=timeLimitHitPost,proto3" json:"time_limit_hit_post,omitempty"`
	MemoryLimitHitPost     bool     `protobuf:"varint,10,opt,name=memory_limit_hit_post,json=memoryLimitHitPost,proto3" json:"memory_limit_hit_post,omitempty"`
	ProcessLimitHit        bool     `protobuf:"varint,11,opt,name=process_limit_hit,json=processLimitHit,proto3" json:"process_limit_hit,omitempty"`
	StoppedBySignal        bool     `protobuf:"varint,12,opt,name=stopped_by_signal,json=stoppedBySignal,proto3" json:"stopped_by_signal,omitempty"`
	KilledBySignal         bool     `protobuf:"varint,13,opt,name=killed_by_signal,json=killedBySignal,proto3" json:"killed_by_signal,omitempty"`
	KernelTimeLimitHit     bool     `protobuf:"varint,14,opt,name=kernel_time_limit_hit,json=kernelTimeLimitHit,proto3" json:"kernel_time_limit_hit,omitempty"`
	KernelTimeLimitHitPost bool     `protobuf:"varint,15,opt,name=kernel_time_limit_hit_post,json=kernelTimeLimitHitPost,proto3" json:"kernel_time_limit_hit_post,omitempty"`
	WallTimeLimitHit       bool     `protobuf:"varint,16,opt,name=wall_time_limit_hit,json=wallTimeLimitHit,proto3" json:"wall_time_limit_hit,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ExecutionResultFlags) Reset()         { *m = ExecutionResultFlags{} }
func (m *ExecutionResultFlags) String() string { return proto.CompactTextString(m) }
func (*ExecutionResultFlags) ProtoMessage()    {}
func (*ExecutionResultFlags) Descriptor() ([]byte, []int) {
	return fileDescriptor_Execution_2061505c8af4a99d, []int{1}
}
func (m *ExecutionResultFlags) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionResultFlags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionResultFlags.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ExecutionResultFlags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionResultFlags.Merge(dst, src)
}
func (m *ExecutionResultFlags) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionResultFlags) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionResultFlags.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionResultFlags proto.InternalMessageInfo

func (m *ExecutionResultFlags) GetKilled() bool {
	if m != nil {
		return m.Killed
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHit() bool {
	if m != nil {
		return m.TimeLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetMemoryLimitHit() bool {
	if m != nil {
		return m.MemoryLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetInactive() bool {
	if m != nil {
		return m.Inactive
	}
	return false
}

func (m *ExecutionResultFlags) GetStdoutOverflow() bool {
	if m != nil {
		return m.StdoutOverflow
	}
	return false
}

func (m *ExecutionResultFlags) GetStderrOverflow() bool {
	if m != nil {
		return m.StderrOverflow
	}
	return false
}

func (m *ExecutionResultFlags) GetStdpipeTimeout() bool {
	if m != nil {
		return m.StdpipeTimeout
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHitPost() bool {
	if m != nil {
		return m.TimeLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetMemoryLimitHitPost() bool {
	if m != nil {
		return m.MemoryLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetProcessLimitHit() bool {
	if m != nil {
		return m.ProcessLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetStoppedBySignal() bool {
	if m != nil {
		return m.StoppedBySignal
	}
	return false
}

func (m *ExecutionResultFlags) GetKilledBySignal() bool {
	if m != nil {
		return m.KilledBySignal
	}
	return false
}

func (m *ExecutionResultFlags) GetKernelTimeLimitHit() bool {
	if m != nil {
		return m.KernelTimeLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetKernelTimeLimitHitPost() bool {
	if m != nil {
		return m.KernelTimeLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetWallTimeLimitHit() bool {
	if m != nil {
		return m.WallTimeLimitHit
	}
	return false
}

type ExecutionResultTime struct {
	UserTimeMicros       uint64   `protobuf:"varint,1,opt,name=user_time_micros,json=userTimeMicros,proto3" json:"user_time_micros,omitempty"`
	KernelTimeMicros     uint64   `protobuf:"varint,2,opt,name=kernel_time_micros,json=kernelTimeMicros,proto3" json:"kernel_time_micros,omitempty"`
	WallTimeMicros       uint64   `protobuf:"varint,3,opt,name=wall_time_micros,json=wallTimeMicros,proto3" json:"wall_time_micros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecutionResultTime) Reset()         { *m = ExecutionResultTime{} }
func (m *ExecutionResultTime) String() string { return proto.CompactTextString(m) }
func (*ExecutionResultTime) ProtoMessage()    {}
func (*ExecutionResultTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_Execution_2061505c8af4a99d, []int{2}
}
func (m *ExecutionResultTime) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionResultTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionResultTime.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ExecutionResultTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionResultTime.Merge(dst, src)
}
func (m *ExecutionResultTime) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionResultTime) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionResultTime.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionResultTime proto.InternalMessageInfo

func (m *ExecutionResultTime) GetUserTimeMicros() uint64 {
	if m != nil {
		return m.UserTimeMicros
	}
	return 0
}

func (m *ExecutionResultTime) GetKernelTimeMicros() uint64 {
	if m != nil {
		return m.KernelTimeMicros
	}
	return 0
}

func (m *ExecutionResultTime) GetWallTimeMicros() uint64 {
	if m != nil {
		return m.WallTimeMicros
	}
	return 0
}

func init() {
	proto.RegisterType((*RedirectParameters)(nil), "contester.proto.RedirectParameters")
	proto.RegisterType((*ExecutionResultFlags)(nil), "contester.proto.ExecutionResultFlags")
	proto.RegisterType((*ExecutionResultTime)(nil), "contester.proto.ExecutionResultTime")
}
func (m *RedirectParameters) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedirectParameters) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Filename) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintExecution(dAtA, i, uint64(len(m.Filename)))
		i += copy(dAtA[i:], m.Filename)
	}
	if m.Memory {
		dAtA[i] = 0x10
		i++
		if m.Memory {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Buffer != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintExecution(dAtA, i, uint64(m.Buffer.Size()))
		n1, err := m.Buffer.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.RemoteFilename) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintExecution(dAtA, i, uint64(len(m.RemoteFilename)))
		i += copy(dAtA[i:], m.RemoteFilename)
	}
	if len(m.RemoteAuthorizationToken) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintExecution(dAtA, i, uint64(len(m.RemoteAuthorizationToken)))
		i += copy(dAtA[i:], m.RemoteAuthorizationToken)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ExecutionResultFlags) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionResultFlags) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Killed {
		dAtA[i] = 0x8
		i++
		if m.Killed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.TimeLimitHit {
		dAtA[i] = 0x10
		i++
		if m.TimeLimitHit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.MemoryLimitHit {
		dAtA[i] = 0x18
		i++
		if m.MemoryLimitHit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Inactive {
		dAtA[i] = 0x20
		i++
		if m.Inactive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.StdoutOverflow {
		dAtA[i] = 0x30
		i++
		if m.StdoutOverflow {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.StderrOverflow {
		dAtA[i] = 0x38
		i++
		if m.StderrOverflow {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.StdpipeTimeout {
		dAtA[i] = 0x40
		i++
		if m.StdpipeTimeout {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.TimeLimitHitPost {
		dAtA[i] = 0x48
		i++
		if m.TimeLimitHitPost {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.MemoryLimitHitPost {
		dAtA[i] = 0x50
		i++
		if m.MemoryLimitHitPost {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.ProcessLimitHit {
		dAtA[i] = 0x58
		i++
		if m.ProcessLimitHit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.StoppedBySignal {
		dAtA[i] = 0x60
		i++
		if m.StoppedBySignal {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.KilledBySignal {
		dAtA[i] = 0x68
		i++
		if m.KilledBySignal {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.KernelTimeLimitHit {
		dAtA[i] = 0x70
		i++
		if m.KernelTimeLimitHit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.KernelTimeLimitHitPost {
		dAtA[i] = 0x78
		i++
		if m.KernelTimeLimitHitPost {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.WallTimeLimitHit {
		dAtA[i] = 0x80
		i++
		dAtA[i] = 0x1
		i++
		if m.WallTimeLimitHit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ExecutionResultTime) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionResultTime) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.UserTimeMicros != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintExecution(dAtA, i, uint64(m.UserTimeMicros))
	}
	if m.KernelTimeMicros != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintExecution(dAtA, i, uint64(m.KernelTimeMicros))
	}
	if m.WallTimeMicros != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintExecution(dAtA, i, uint64(m.WallTimeMicros))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintExecution(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RedirectParameters) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Filename)
	if l > 0 {
		n += 1 + l + sovExecution(uint64(l))
	}
	if m.Memory {
		n += 2
	}
	if m.Buffer != nil {
		l = m.Buffer.Size()
		n += 1 + l + sovExecution(uint64(l))
	}
	l = len(m.RemoteFilename)
	if l > 0 {
		n += 1 + l + sovExecution(uint64(l))
	}
	l = len(m.RemoteAuthorizationToken)
	if l > 0 {
		n += 1 + l + sovExecution(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ExecutionResultFlags) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Killed {
		n += 2
	}
	if m.TimeLimitHit {
		n += 2
	}
	if m.MemoryLimitHit {
		n += 2
	}
	if m.Inactive {
		n += 2
	}
	if m.StdoutOverflow {
		n += 2
	}
	if m.StderrOverflow {
		n += 2
	}
	if m.StdpipeTimeout {
		n += 2
	}
	if m.TimeLimitHitPost {
		n += 2
	}
	if m.MemoryLimitHitPost {
		n += 2
	}
	if m.ProcessLimitHit {
		n += 2
	}
	if m.StoppedBySignal {
		n += 2
	}
	if m.KilledBySignal {
		n += 2
	}
	if m.KernelTimeLimitHit {
		n += 2
	}
	if m.KernelTimeLimitHitPost {
		n += 2
	}
	if m.WallTimeLimitHit {
		n += 3
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ExecutionResultTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserTimeMicros != 0 {
		n += 1 + sovExecution(uint64(m.UserTimeMicros))
	}
	if m.KernelTimeMicros != 0 {
		n += 1 + sovExecution(uint64(m.KernelTimeMicros))
	}
	if m.WallTimeMicros != 0 {
		n += 1 + sovExecution(uint64(m.WallTimeMicros))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovExecution(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozExecution(x uint64) (n int) {
	return sovExecution(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RedirectParameters) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedirectParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedirectParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecution
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Memory = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExecution
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Buffer == nil {
				m.Buffer = &Blob{}
			}
			if err := m.Buffer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteFilename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecution
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteFilename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteAuthorizationToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecution
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteAuthorizationToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExecution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExecution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionResultFlags) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionResultFlags: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionResultFlags: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Killed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Killed = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeLimitHit = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MemoryLimitHit = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inactive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Inactive = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StdoutOverflow", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StdoutOverflow = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StderrOverflow", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StderrOverflow = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StdpipeTimeout", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StdpipeTimeout = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLimitHitPost", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TimeLimitHitPost = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryLimitHitPost", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MemoryLimitHitPost = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ProcessLimitHit = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoppedBySignal", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.StoppedBySignal = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KilledBySignal", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.KilledBySignal = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelTimeLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.KernelTimeLimitHit = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelTimeLimitHitPost", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.KernelTimeLimitHitPost = bool(v != 0)
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WallTimeLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WallTimeLimitHit = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipExecution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExecution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionResultTime) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionResultTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionResultTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserTimeMicros", wireType)
			}
			m.UserTimeMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserTimeMicros |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelTimeMicros", wireType)
			}
			m.KernelTimeMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KernelTimeMicros |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WallTimeMicros", wireType)
			}
			m.WallTimeMicros = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WallTimeMicros |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipExecution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExecution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExecution(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthExecution
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowExecution
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipExecution(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthExecution = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExecution   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("Execution.proto", fileDescriptor_Execution_2061505c8af4a99d) }

var fileDescriptor_Execution_2061505c8af4a99d = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x86, 0x3f, 0xf7, 0x27, 0x9f, 0x3b, 0x2d, 0x49, 0xba, 0x21, 0x95, 0x15, 0xa1, 0x28, 0x8a,
	0x90, 0x88, 0x2a, 0x12, 0xa9, 0x70, 0x86, 0x38, 0x21, 0x12, 0x15, 0x07, 0x20, 0x2a, 0x93, 0x73,
	0xcb, 0x71, 0x26, 0xe9, 0x2a, 0x6b, 0xaf, 0xb5, 0xbb, 0x6e, 0x09, 0x37, 0x52, 0x2e, 0x89, 0x43,
	0xae, 0x00, 0xa1, 0x70, 0x23, 0x68, 0x7f, 0xea, 0xb8, 0x2e, 0x47, 0xd6, 0xbc, 0xf3, 0xcc, 0xce,
	0xbc, 0xb3, 0x6b, 0x68, 0xbd, 0xff, 0x8a, 0x49, 0xa1, 0x28, 0xcf, 0x26, 0xb9, 0xe0, 0x8a, 0x93,
	0x56, 0xc2, 0x33, 0x85, 0x52, 0xa1, 0xb0, 0x42, 0xef, 0x78, 0xca, 0xf8, 0x5c, 0xda, 0x60, 0xf8,
	0xcb, 0x03, 0x12, 0xe2, 0x82, 0x0a, 0x4c, 0xd4, 0x55, 0x2c, 0xe2, 0x14, 0x15, 0x0a, 0x49, 0x7a,
	0xe0, 0x2f, 0x29, 0xc3, 0x2c, 0x4e, 0x31, 0xf0, 0x06, 0xde, 0xe8, 0x28, 0x2c, 0x63, 0x72, 0x06,
	0x8d, 0x14, 0x53, 0x2e, 0x36, 0xc1, 0xde, 0xc0, 0x1b, 0xf9, 0xa1, 0x8b, 0xc8, 0x18, 0x1a, 0xf3,
	0x62, 0xb9, 0x44, 0x11, 0xec, 0x0f, 0xbc, 0xd1, 0xf1, 0xab, 0xee, 0xa4, 0xd6, 0x79, 0xa2, 0x1b,
	0x87, 0x0e, 0x22, 0x2f, 0xa0, 0x25, 0x30, 0xe5, 0x0a, 0xa3, 0xb2, 0xd3, 0x81, 0xe9, 0xd4, 0xb4,
	0xf2, 0xe5, 0x7d, 0xbf, 0xb7, 0xd0, 0x73, 0x60, 0x5c, 0xa8, 0x6b, 0x2e, 0xe8, 0xb7, 0x58, 0xdb,
	0x8b, 0x14, 0x5f, 0x63, 0x16, 0x1c, 0x9a, 0x9a, 0xc0, 0x12, 0xef, 0xaa, 0xc0, 0x4c, 0xe7, 0x87,
	0x77, 0x87, 0xf0, 0xb4, 0x5c, 0x49, 0x88, 0xb2, 0x60, 0xea, 0x92, 0xc5, 0x2b, 0xa9, 0x6d, 0xac,
	0x29, 0x63, 0xb8, 0x30, 0x06, 0xfd, 0xd0, 0x45, 0xe4, 0x39, 0x34, 0x15, 0x4d, 0x31, 0x62, 0x34,
	0xa5, 0x2a, 0xba, 0xa6, 0xca, 0xd9, 0x3c, 0xd1, 0xea, 0x47, 0x2d, 0x7e, 0xa0, 0x8a, 0x8c, 0xa0,
	0x6d, 0x6d, 0x57, 0xb8, 0x7d, 0xc3, 0x35, 0xad, 0x5e, 0x92, 0x3d, 0xf0, 0x69, 0x16, 0x27, 0x8a,
	0xde, 0x58, 0x83, 0x7e, 0x58, 0xc6, 0x7a, 0x07, 0x52, 0x2d, 0x78, 0xa1, 0x22, 0x7e, 0x83, 0x62,
	0xc9, 0xf8, 0x6d, 0xd0, 0xb0, 0x87, 0x58, 0xf9, 0xb3, 0x53, 0x1d, 0x88, 0x42, 0xec, 0xc0, 0xff,
	0x4b, 0x10, 0x85, 0xa8, 0x81, 0x39, 0xcd, 0x31, 0xd2, 0xf3, 0xf2, 0x42, 0x05, 0x7e, 0x09, 0x6a,
	0x79, 0x66, 0x55, 0x32, 0x86, 0xce, 0x43, 0x9b, 0x51, 0xce, 0xa5, 0x0a, 0x8e, 0x0c, 0xdc, 0xae,
	0x7a, 0xbd, 0xe2, 0x52, 0x91, 0x0b, 0xe8, 0xd6, 0xfd, 0xda, 0x02, 0x30, 0x05, 0xe4, 0xa1, 0x69,
	0x53, 0x72, 0x0e, 0xa7, 0xb9, 0xe0, 0x09, 0x4a, 0x59, 0xd9, 0xd1, 0xb1, 0xc1, 0x5b, 0x2e, 0x51,
	0x2e, 0xe9, 0x1c, 0x4e, 0xa5, 0xe2, 0x79, 0x8e, 0x8b, 0x68, 0xbe, 0x89, 0x24, 0x5d, 0x65, 0x31,
	0x0b, 0x4e, 0x2c, 0xeb, 0x12, 0xd3, 0xcd, 0x17, 0x23, 0xeb, 0xd5, 0xdb, 0xab, 0xaa, 0xa0, 0x4f,
	0xac, 0x47, 0xab, 0x97, 0xe4, 0x05, 0x74, 0xd7, 0x28, 0x32, 0x64, 0x51, 0xed, 0x46, 0x9b, 0x76,
	0x68, 0x9b, 0x9c, 0x55, 0xef, 0xf5, 0x0d, 0xf4, 0xfe, 0x59, 0x62, 0xcd, 0xb6, 0x4c, 0xdd, 0xd9,
	0xe3, 0x3a, 0x63, 0x78, 0x0c, 0x9d, 0xdb, 0x98, 0x3d, 0x6a, 0xd6, 0xb6, 0x2b, 0xd5, 0xa9, 0x6a,
	0xc9, 0xf0, 0xce, 0x83, 0x4e, 0xed, 0x65, 0xea, 0xbc, 0xf6, 0x57, 0x48, 0x14, 0xf6, 0x98, 0x94,
	0x26, 0x82, 0x4b, 0xf3, 0x44, 0x0f, 0xc2, 0xa6, 0xd6, 0x35, 0xf3, 0xc9, 0xa8, 0xe4, 0x25, 0x90,
	0xea, 0xb0, 0x8e, 0xdd, 0x33, 0x6c, 0x7b, 0x37, 0xa4, 0xa3, 0x47, 0xd0, 0xde, 0x8d, 0xe7, 0xd8,
	0x7d, 0x7b, 0xee, 0xfd, 0x6c, 0x96, 0x9c, 0x4e, 0x7e, 0x6c, 0xfb, 0xde, 0xcf, 0x6d, 0xdf, 0xfb,
	0xbd, 0xed, 0x7b, 0xdf, 0xff, 0xf4, 0xff, 0x83, 0x67, 0x5c, 0xac, 0x26, 0x52, 0xd1, 0x6c, 0x25,
	0xe2, 0x4d, 0xfd, 0xbf, 0x9e, 0x37, 0xcc, 0xe7, 0xf5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0x31, 0x84, 0xde, 0x7c, 0x04, 0x00, 0x00,
}
