// Code generated by protoc-gen-gogo.
// source: Execution.proto
// DO NOT EDIT!

package contester_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RedirectParameters struct {
	Filename         *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Memory           *bool   `protobuf:"varint,2,opt,name=memory" json:"memory,omitempty"`
	Buffer           *Blob   `protobuf:"bytes,3,opt,name=buffer" json:"buffer,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RedirectParameters) Reset()                    { *m = RedirectParameters{} }
func (m *RedirectParameters) String() string            { return proto.CompactTextString(m) }
func (*RedirectParameters) ProtoMessage()               {}
func (*RedirectParameters) Descriptor() ([]byte, []int) { return fileDescriptorExecution, []int{0} }

func (m *RedirectParameters) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *RedirectParameters) GetMemory() bool {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return false
}

func (m *RedirectParameters) GetBuffer() *Blob {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type ExecutionResultFlags struct {
	Killed             *bool  `protobuf:"varint,1,opt,name=killed" json:"killed,omitempty"`
	TimeLimitHit       *bool  `protobuf:"varint,2,opt,name=time_limit_hit,json=timeLimitHit" json:"time_limit_hit,omitempty"`
	MemoryLimitHit     *bool  `protobuf:"varint,3,opt,name=memory_limit_hit,json=memoryLimitHit" json:"memory_limit_hit,omitempty"`
	Inactive           *bool  `protobuf:"varint,4,opt,name=inactive" json:"inactive,omitempty"`
	TimeLimitHard      *bool  `protobuf:"varint,5,opt,name=time_limit_hard,json=timeLimitHard" json:"time_limit_hard,omitempty"`
	StdoutOverflow     *bool  `protobuf:"varint,6,opt,name=stdout_overflow,json=stdoutOverflow" json:"stdout_overflow,omitempty"`
	StderrOverflow     *bool  `protobuf:"varint,7,opt,name=stderr_overflow,json=stderrOverflow" json:"stderr_overflow,omitempty"`
	StdpipeTimeout     *bool  `protobuf:"varint,8,opt,name=stdpipe_timeout,json=stdpipeTimeout" json:"stdpipe_timeout,omitempty"`
	TimeLimitHitPost   *bool  `protobuf:"varint,9,opt,name=time_limit_hit_post,json=timeLimitHitPost" json:"time_limit_hit_post,omitempty"`
	MemoryLimitHitPost *bool  `protobuf:"varint,10,opt,name=memory_limit_hit_post,json=memoryLimitHitPost" json:"memory_limit_hit_post,omitempty"`
	ProcessLimitHit    *bool  `protobuf:"varint,11,opt,name=process_limit_hit,json=processLimitHit" json:"process_limit_hit,omitempty"`
	StoppedBySignal    *bool  `protobuf:"varint,12,opt,name=stopped_by_signal,json=stoppedBySignal" json:"stopped_by_signal,omitempty"`
	KilledBySignal     *bool  `protobuf:"varint,13,opt,name=killed_by_signal,json=killedBySignal" json:"killed_by_signal,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *ExecutionResultFlags) Reset()                    { *m = ExecutionResultFlags{} }
func (m *ExecutionResultFlags) String() string            { return proto.CompactTextString(m) }
func (*ExecutionResultFlags) ProtoMessage()               {}
func (*ExecutionResultFlags) Descriptor() ([]byte, []int) { return fileDescriptorExecution, []int{1} }

func (m *ExecutionResultFlags) GetKilled() bool {
	if m != nil && m.Killed != nil {
		return *m.Killed
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHit() bool {
	if m != nil && m.TimeLimitHit != nil {
		return *m.TimeLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetMemoryLimitHit() bool {
	if m != nil && m.MemoryLimitHit != nil {
		return *m.MemoryLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetInactive() bool {
	if m != nil && m.Inactive != nil {
		return *m.Inactive
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHard() bool {
	if m != nil && m.TimeLimitHard != nil {
		return *m.TimeLimitHard
	}
	return false
}

func (m *ExecutionResultFlags) GetStdoutOverflow() bool {
	if m != nil && m.StdoutOverflow != nil {
		return *m.StdoutOverflow
	}
	return false
}

func (m *ExecutionResultFlags) GetStderrOverflow() bool {
	if m != nil && m.StderrOverflow != nil {
		return *m.StderrOverflow
	}
	return false
}

func (m *ExecutionResultFlags) GetStdpipeTimeout() bool {
	if m != nil && m.StdpipeTimeout != nil {
		return *m.StdpipeTimeout
	}
	return false
}

func (m *ExecutionResultFlags) GetTimeLimitHitPost() bool {
	if m != nil && m.TimeLimitHitPost != nil {
		return *m.TimeLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetMemoryLimitHitPost() bool {
	if m != nil && m.MemoryLimitHitPost != nil {
		return *m.MemoryLimitHitPost
	}
	return false
}

func (m *ExecutionResultFlags) GetProcessLimitHit() bool {
	if m != nil && m.ProcessLimitHit != nil {
		return *m.ProcessLimitHit
	}
	return false
}

func (m *ExecutionResultFlags) GetStoppedBySignal() bool {
	if m != nil && m.StoppedBySignal != nil {
		return *m.StoppedBySignal
	}
	return false
}

func (m *ExecutionResultFlags) GetKilledBySignal() bool {
	if m != nil && m.KilledBySignal != nil {
		return *m.KilledBySignal
	}
	return false
}

type ExecutionResultTime struct {
	UserTimeMicros   *uint64 `protobuf:"varint,1,opt,name=user_time_micros,json=userTimeMicros" json:"user_time_micros,omitempty"`
	KernelTimeMicros *uint64 `protobuf:"varint,2,opt,name=kernel_time_micros,json=kernelTimeMicros" json:"kernel_time_micros,omitempty"`
	WallTimeMicros   *uint64 `protobuf:"varint,3,opt,name=wall_time_micros,json=wallTimeMicros" json:"wall_time_micros,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ExecutionResultTime) Reset()                    { *m = ExecutionResultTime{} }
func (m *ExecutionResultTime) String() string            { return proto.CompactTextString(m) }
func (*ExecutionResultTime) ProtoMessage()               {}
func (*ExecutionResultTime) Descriptor() ([]byte, []int) { return fileDescriptorExecution, []int{2} }

func (m *ExecutionResultTime) GetUserTimeMicros() uint64 {
	if m != nil && m.UserTimeMicros != nil {
		return *m.UserTimeMicros
	}
	return 0
}

func (m *ExecutionResultTime) GetKernelTimeMicros() uint64 {
	if m != nil && m.KernelTimeMicros != nil {
		return *m.KernelTimeMicros
	}
	return 0
}

func (m *ExecutionResultTime) GetWallTimeMicros() uint64 {
	if m != nil && m.WallTimeMicros != nil {
		return *m.WallTimeMicros
	}
	return 0
}

func init() {
	proto.RegisterType((*RedirectParameters)(nil), "contester.proto.RedirectParameters")
	proto.RegisterType((*ExecutionResultFlags)(nil), "contester.proto.ExecutionResultFlags")
	proto.RegisterType((*ExecutionResultTime)(nil), "contester.proto.ExecutionResultTime")
}
func (m *RedirectParameters) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *RedirectParameters) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Filename != nil {
		data[i] = 0xa
		i++
		i = encodeVarintExecution(data, i, uint64(len(*m.Filename)))
		i += copy(data[i:], *m.Filename)
	}
	if m.Memory != nil {
		data[i] = 0x10
		i++
		if *m.Memory {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.Buffer != nil {
		data[i] = 0x1a
		i++
		i = encodeVarintExecution(data, i, uint64(m.Buffer.Size()))
		n1, err := m.Buffer.MarshalTo(data[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ExecutionResultFlags) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ExecutionResultFlags) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Killed != nil {
		data[i] = 0x8
		i++
		if *m.Killed {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.TimeLimitHit != nil {
		data[i] = 0x10
		i++
		if *m.TimeLimitHit {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.MemoryLimitHit != nil {
		data[i] = 0x18
		i++
		if *m.MemoryLimitHit {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.Inactive != nil {
		data[i] = 0x20
		i++
		if *m.Inactive {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.TimeLimitHard != nil {
		data[i] = 0x28
		i++
		if *m.TimeLimitHard {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.StdoutOverflow != nil {
		data[i] = 0x30
		i++
		if *m.StdoutOverflow {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.StderrOverflow != nil {
		data[i] = 0x38
		i++
		if *m.StderrOverflow {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.StdpipeTimeout != nil {
		data[i] = 0x40
		i++
		if *m.StdpipeTimeout {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.TimeLimitHitPost != nil {
		data[i] = 0x48
		i++
		if *m.TimeLimitHitPost {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.MemoryLimitHitPost != nil {
		data[i] = 0x50
		i++
		if *m.MemoryLimitHitPost {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.ProcessLimitHit != nil {
		data[i] = 0x58
		i++
		if *m.ProcessLimitHit {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.StoppedBySignal != nil {
		data[i] = 0x60
		i++
		if *m.StoppedBySignal {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.KilledBySignal != nil {
		data[i] = 0x68
		i++
		if *m.KilledBySignal {
			data[i] = 1
		} else {
			data[i] = 0
		}
		i++
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ExecutionResultTime) Marshal() (data []byte, err error) {
	size := m.Size()
	data = make([]byte, size)
	n, err := m.MarshalTo(data)
	if err != nil {
		return nil, err
	}
	return data[:n], nil
}

func (m *ExecutionResultTime) MarshalTo(data []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.UserTimeMicros != nil {
		data[i] = 0x8
		i++
		i = encodeVarintExecution(data, i, uint64(*m.UserTimeMicros))
	}
	if m.KernelTimeMicros != nil {
		data[i] = 0x10
		i++
		i = encodeVarintExecution(data, i, uint64(*m.KernelTimeMicros))
	}
	if m.WallTimeMicros != nil {
		data[i] = 0x18
		i++
		i = encodeVarintExecution(data, i, uint64(*m.WallTimeMicros))
	}
	if m.XXX_unrecognized != nil {
		i += copy(data[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeFixed64Execution(data []byte, offset int, v uint64) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	data[offset+4] = uint8(v >> 32)
	data[offset+5] = uint8(v >> 40)
	data[offset+6] = uint8(v >> 48)
	data[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Execution(data []byte, offset int, v uint32) int {
	data[offset] = uint8(v)
	data[offset+1] = uint8(v >> 8)
	data[offset+2] = uint8(v >> 16)
	data[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintExecution(data []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		data[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	data[offset] = uint8(v)
	return offset + 1
}
func (m *RedirectParameters) Size() (n int) {
	var l int
	_ = l
	if m.Filename != nil {
		l = len(*m.Filename)
		n += 1 + l + sovExecution(uint64(l))
	}
	if m.Memory != nil {
		n += 2
	}
	if m.Buffer != nil {
		l = m.Buffer.Size()
		n += 1 + l + sovExecution(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ExecutionResultFlags) Size() (n int) {
	var l int
	_ = l
	if m.Killed != nil {
		n += 2
	}
	if m.TimeLimitHit != nil {
		n += 2
	}
	if m.MemoryLimitHit != nil {
		n += 2
	}
	if m.Inactive != nil {
		n += 2
	}
	if m.TimeLimitHard != nil {
		n += 2
	}
	if m.StdoutOverflow != nil {
		n += 2
	}
	if m.StderrOverflow != nil {
		n += 2
	}
	if m.StdpipeTimeout != nil {
		n += 2
	}
	if m.TimeLimitHitPost != nil {
		n += 2
	}
	if m.MemoryLimitHitPost != nil {
		n += 2
	}
	if m.ProcessLimitHit != nil {
		n += 2
	}
	if m.StoppedBySignal != nil {
		n += 2
	}
	if m.KilledBySignal != nil {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ExecutionResultTime) Size() (n int) {
	var l int
	_ = l
	if m.UserTimeMicros != nil {
		n += 1 + sovExecution(uint64(*m.UserTimeMicros))
	}
	if m.KernelTimeMicros != nil {
		n += 1 + sovExecution(uint64(*m.KernelTimeMicros))
	}
	if m.WallTimeMicros != nil {
		n += 1 + sovExecution(uint64(*m.WallTimeMicros))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovExecution(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozExecution(x uint64) (n int) {
	return sovExecution(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RedirectParameters) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedirectParameters: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedirectParameters: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExecution
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(data[iNdEx:postIndex])
			m.Filename = &s
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memory", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Memory = &b
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthExecution
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Buffer == nil {
				m.Buffer = &Blob{}
			}
			if err := m.Buffer.Unmarshal(data[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipExecution(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExecution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionResultFlags) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionResultFlags: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionResultFlags: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Killed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Killed = &b
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.TimeLimitHit = &b
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.MemoryLimitHit = &b
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inactive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.Inactive = &b
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLimitHard", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.TimeLimitHard = &b
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StdoutOverflow", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.StdoutOverflow = &b
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StderrOverflow", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.StderrOverflow = &b
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StdpipeTimeout", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.StdpipeTimeout = &b
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLimitHitPost", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.TimeLimitHitPost = &b
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryLimitHitPost", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.MemoryLimitHitPost = &b
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessLimitHit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.ProcessLimitHit = &b
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoppedBySignal", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.StoppedBySignal = &b
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KilledBySignal", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.KilledBySignal = &b
		default:
			iNdEx = preIndex
			skippy, err := skipExecution(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExecution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionResultTime) Unmarshal(data []byte) error {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionResultTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionResultTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserTimeMicros", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.UserTimeMicros = &v
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KernelTimeMicros", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.KernelTimeMicros = &v
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WallTimeMicros", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WallTimeMicros = &v
		default:
			iNdEx = preIndex
			skippy, err := skipExecution(data[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthExecution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, data[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExecution(data []byte) (n int, err error) {
	l := len(data)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExecution
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := data[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if data[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExecution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := data[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthExecution
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowExecution
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := data[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipExecution(data[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthExecution = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExecution   = fmt.Errorf("proto: integer overflow")
)

var fileDescriptorExecution = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x92, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0xe9, 0x5a, 0x4a, 0xe7, 0x6e, 0x4d, 0xf1, 0x18, 0xb2, 0x26, 0x34, 0xa1, 0x0a, 0xc1,
	0x84, 0x20, 0x12, 0x3c, 0x42, 0x25, 0x10, 0x17, 0x20, 0xa6, 0xc0, 0x7d, 0xe4, 0x26, 0xa7, 0xc5,
	0x9a, 0x13, 0x47, 0xb6, 0xb3, 0xd2, 0x27, 0x81, 0x5b, 0xde, 0x86, 0x4b, 0x1e, 0x01, 0xc1, 0x8b,
	0x70, 0x6c, 0x87, 0x34, 0xcd, 0x45, 0x2e, 0xce, 0xe7, 0xcf, 0xe7, 0xc4, 0xbf, 0x4d, 0xa2, 0x37,
	0x5f, 0x21, 0xab, 0xad, 0x50, 0x65, 0x5c, 0x69, 0x65, 0x15, 0x8d, 0x32, 0x55, 0x5a, 0x30, 0x16,
	0x74, 0x00, 0x17, 0xd3, 0xa5, 0x54, 0x2b, 0x13, 0x8a, 0xc5, 0x96, 0xd0, 0x04, 0x72, 0xa1, 0x21,
	0xb3, 0xd7, 0x5c, 0xf3, 0x02, 0xd0, 0x33, 0xf4, 0x82, 0x4c, 0xd6, 0x42, 0x42, 0x89, 0x35, 0x1b,
	0x3c, 0x1e, 0x5c, 0x1d, 0x27, 0x6d, 0x4d, 0x1f, 0x92, 0x71, 0x01, 0x85, 0xd2, 0x3b, 0x76, 0x84,
	0x2b, 0x93, 0xa4, 0xa9, 0xe8, 0x4b, 0x32, 0x5e, 0xd5, 0xeb, 0x35, 0x68, 0x36, 0x44, 0x3e, 0x7d,
	0x7d, 0x1e, 0xf7, 0x06, 0xc7, 0x6e, 0x6e, 0xd2, 0x48, 0x8b, 0x1f, 0x23, 0xf2, 0xa0, 0xfd, 0xd5,
	0x04, 0x4c, 0x2d, 0xed, 0x5b, 0xc9, 0x37, 0xc6, 0xf5, 0xbf, 0x11, 0x52, 0x42, 0xee, 0x27, 0x63,
	0xff, 0x50, 0xd1, 0x27, 0x64, 0x66, 0x45, 0x01, 0xa9, 0x14, 0x85, 0xb0, 0xe9, 0x17, 0x61, 0x9b,
	0xf9, 0x27, 0x8e, 0xbe, 0x77, 0xf0, 0x9d, 0xb0, 0xf4, 0x8a, 0xcc, 0xc3, 0xff, 0x74, 0xbc, 0xa1,
	0xf7, 0x66, 0x81, 0xb7, 0x26, 0x9e, 0x51, 0x94, 0x3c, 0xb3, 0xe2, 0x16, 0xd8, 0xc8, 0x1b, 0x6d,
	0x4d, 0x9f, 0x92, 0xa8, 0x3b, 0x8b, 0xeb, 0x9c, 0xdd, 0xf5, 0xca, 0xe9, 0x7e, 0x18, 0x42, 0xfa,
	0x8c, 0x44, 0xc6, 0xe6, 0xaa, 0xb6, 0xa9, 0xba, 0x05, 0xbd, 0x96, 0x6a, 0xcb, 0xc6, 0x61, 0x58,
	0xc0, 0x1f, 0x1b, 0xda, 0x88, 0xa0, 0xf5, 0x5e, 0xbc, 0xd7, 0x8a, 0x88, 0x7b, 0x62, 0x25, 0x2a,
	0x48, 0xdd, 0x28, 0xec, 0xc1, 0x26, 0xad, 0xe8, 0xf0, 0xe7, 0x40, 0x31, 0xee, 0xb3, 0xc3, 0x38,
	0xd2, 0x4a, 0x19, 0xcb, 0x8e, 0xbd, 0x3c, 0xef, 0x66, 0x72, 0x8d, 0x9c, 0xbe, 0x22, 0xe7, 0xfd,
	0x5c, 0xc2, 0x06, 0xe2, 0x37, 0xd0, 0xc3, 0x70, 0xfc, 0x96, 0xe7, 0xe4, 0x3e, 0xde, 0x5b, 0x06,
	0xc6, 0x74, 0xb2, 0x9c, 0x7a, 0x3d, 0x6a, 0x16, 0xda, 0x30, 0xd1, 0x35, 0x56, 0x55, 0x15, 0xe4,
	0xe9, 0x6a, 0x97, 0x1a, 0xb1, 0x29, 0xb9, 0x64, 0x27, 0xc1, 0x6d, 0x16, 0x96, 0xbb, 0x4f, 0x1e,
	0xbb, 0x2b, 0x0a, 0x57, 0xda, 0x51, 0x4f, 0xc3, 0x19, 0x03, 0xff, 0x6f, 0x2e, 0xbe, 0x0d, 0xc8,
	0x59, 0xef, 0x8d, 0xb8, 0xe3, 0xbb, 0x0e, 0xb5, 0x01, 0xed, 0x13, 0x4a, 0x0b, 0x91, 0x69, 0x65,
	0xfc, 0x63, 0x19, 0x25, 0x33, 0xc7, 0x9d, 0xf3, 0xc1, 0x53, 0xfa, 0x82, 0xd0, 0x1b, 0xd0, 0x25,
	0xc8, 0x03, 0xf7, 0xc8, 0xbb, 0xf3, 0xb0, 0xd2, 0xb1, 0xb1, 0xef, 0x96, 0xcb, 0x43, 0x77, 0x18,
	0xfa, 0x3a, 0xbe, 0x37, 0x97, 0xf1, 0xcf, 0x3f, 0x97, 0x83, 0x5f, 0xf8, 0xfd, 0xc6, 0xef, 0xfb,
	0xdf, 0xcb, 0x3b, 0xe4, 0x91, 0xd2, 0x9b, 0xd8, 0x58, 0x51, 0x6e, 0x34, 0xdf, 0xf5, 0x9f, 0xfe,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xb5, 0x4f, 0x34, 0x96, 0x03, 0x00, 0x00,
}
