// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: Execution.proto

//go:build protoopaque

package contester_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedirectParameters struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filename                 string                 `protobuf:"bytes,1,opt,name=filename"`
	xxx_hidden_Memory                   bool                   `protobuf:"varint,2,opt,name=memory"`
	xxx_hidden_Buffer                   *Blob                  `protobuf:"bytes,3,opt,name=buffer"`
	xxx_hidden_RemoteFilename           string                 `protobuf:"bytes,4,opt,name=remote_filename,json=remoteFilename"`
	xxx_hidden_RemoteAuthorizationToken string                 `protobuf:"bytes,5,opt,name=remote_authorization_token,json=remoteAuthorizationToken"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *RedirectParameters) Reset() {
	*x = RedirectParameters{}
	mi := &file_Execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectParameters) ProtoMessage() {}

func (x *RedirectParameters) ProtoReflect() protoreflect.Message {
	mi := &file_Execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RedirectParameters) GetFilename() string {
	if x != nil {
		return x.xxx_hidden_Filename
	}
	return ""
}

func (x *RedirectParameters) GetMemory() bool {
	if x != nil {
		return x.xxx_hidden_Memory
	}
	return false
}

func (x *RedirectParameters) GetBuffer() *Blob {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *RedirectParameters) GetRemoteFilename() string {
	if x != nil {
		return x.xxx_hidden_RemoteFilename
	}
	return ""
}

func (x *RedirectParameters) GetRemoteAuthorizationToken() string {
	if x != nil {
		return x.xxx_hidden_RemoteAuthorizationToken
	}
	return ""
}

func (x *RedirectParameters) SetFilename(v string) {
	x.xxx_hidden_Filename = v
}

func (x *RedirectParameters) SetMemory(v bool) {
	x.xxx_hidden_Memory = v
}

func (x *RedirectParameters) SetBuffer(v *Blob) {
	x.xxx_hidden_Buffer = v
}

func (x *RedirectParameters) SetRemoteFilename(v string) {
	x.xxx_hidden_RemoteFilename = v
}

func (x *RedirectParameters) SetRemoteAuthorizationToken(v string) {
	x.xxx_hidden_RemoteAuthorizationToken = v
}

func (x *RedirectParameters) HasBuffer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Buffer != nil
}

func (x *RedirectParameters) ClearBuffer() {
	x.xxx_hidden_Buffer = nil
}

type RedirectParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Filename                 string
	Memory                   bool
	Buffer                   *Blob
	RemoteFilename           string
	RemoteAuthorizationToken string
}

func (b0 RedirectParameters_builder) Build() *RedirectParameters {
	m0 := &RedirectParameters{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filename = b.Filename
	x.xxx_hidden_Memory = b.Memory
	x.xxx_hidden_Buffer = b.Buffer
	x.xxx_hidden_RemoteFilename = b.RemoteFilename
	x.xxx_hidden_RemoteAuthorizationToken = b.RemoteAuthorizationToken
	return m0
}

type ExecutionResultFlags struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Killed                 bool                   `protobuf:"varint,1,opt,name=killed"`
	xxx_hidden_TimeLimitHit           bool                   `protobuf:"varint,2,opt,name=time_limit_hit,json=timeLimitHit"`
	xxx_hidden_MemoryLimitHit         bool                   `protobuf:"varint,3,opt,name=memory_limit_hit,json=memoryLimitHit"`
	xxx_hidden_Inactive               bool                   `protobuf:"varint,4,opt,name=inactive"`
	xxx_hidden_StdoutOverflow         bool                   `protobuf:"varint,6,opt,name=stdout_overflow,json=stdoutOverflow"`
	xxx_hidden_StderrOverflow         bool                   `protobuf:"varint,7,opt,name=stderr_overflow,json=stderrOverflow"`
	xxx_hidden_StdpipeTimeout         bool                   `protobuf:"varint,8,opt,name=stdpipe_timeout,json=stdpipeTimeout"`
	xxx_hidden_TimeLimitHitPost       bool                   `protobuf:"varint,9,opt,name=time_limit_hit_post,json=timeLimitHitPost"`
	xxx_hidden_MemoryLimitHitPost     bool                   `protobuf:"varint,10,opt,name=memory_limit_hit_post,json=memoryLimitHitPost"`
	xxx_hidden_ProcessLimitHit        bool                   `protobuf:"varint,11,opt,name=process_limit_hit,json=processLimitHit"`
	xxx_hidden_StoppedBySignal        bool                   `protobuf:"varint,12,opt,name=stopped_by_signal,json=stoppedBySignal"`
	xxx_hidden_KilledBySignal         bool                   `protobuf:"varint,13,opt,name=killed_by_signal,json=killedBySignal"`
	xxx_hidden_KernelTimeLimitHit     bool                   `protobuf:"varint,14,opt,name=kernel_time_limit_hit,json=kernelTimeLimitHit"`
	xxx_hidden_KernelTimeLimitHitPost bool                   `protobuf:"varint,15,opt,name=kernel_time_limit_hit_post,json=kernelTimeLimitHitPost"`
	xxx_hidden_WallTimeLimitHit       bool                   `protobuf:"varint,16,opt,name=wall_time_limit_hit,json=wallTimeLimitHit"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ExecutionResultFlags) Reset() {
	*x = ExecutionResultFlags{}
	mi := &file_Execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResultFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResultFlags) ProtoMessage() {}

func (x *ExecutionResultFlags) ProtoReflect() protoreflect.Message {
	mi := &file_Execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecutionResultFlags) GetKilled() bool {
	if x != nil {
		return x.xxx_hidden_Killed
	}
	return false
}

func (x *ExecutionResultFlags) GetTimeLimitHit() bool {
	if x != nil {
		return x.xxx_hidden_TimeLimitHit
	}
	return false
}

func (x *ExecutionResultFlags) GetMemoryLimitHit() bool {
	if x != nil {
		return x.xxx_hidden_MemoryLimitHit
	}
	return false
}

func (x *ExecutionResultFlags) GetInactive() bool {
	if x != nil {
		return x.xxx_hidden_Inactive
	}
	return false
}

func (x *ExecutionResultFlags) GetStdoutOverflow() bool {
	if x != nil {
		return x.xxx_hidden_StdoutOverflow
	}
	return false
}

func (x *ExecutionResultFlags) GetStderrOverflow() bool {
	if x != nil {
		return x.xxx_hidden_StderrOverflow
	}
	return false
}

func (x *ExecutionResultFlags) GetStdpipeTimeout() bool {
	if x != nil {
		return x.xxx_hidden_StdpipeTimeout
	}
	return false
}

func (x *ExecutionResultFlags) GetTimeLimitHitPost() bool {
	if x != nil {
		return x.xxx_hidden_TimeLimitHitPost
	}
	return false
}

func (x *ExecutionResultFlags) GetMemoryLimitHitPost() bool {
	if x != nil {
		return x.xxx_hidden_MemoryLimitHitPost
	}
	return false
}

func (x *ExecutionResultFlags) GetProcessLimitHit() bool {
	if x != nil {
		return x.xxx_hidden_ProcessLimitHit
	}
	return false
}

func (x *ExecutionResultFlags) GetStoppedBySignal() bool {
	if x != nil {
		return x.xxx_hidden_StoppedBySignal
	}
	return false
}

func (x *ExecutionResultFlags) GetKilledBySignal() bool {
	if x != nil {
		return x.xxx_hidden_KilledBySignal
	}
	return false
}

func (x *ExecutionResultFlags) GetKernelTimeLimitHit() bool {
	if x != nil {
		return x.xxx_hidden_KernelTimeLimitHit
	}
	return false
}

func (x *ExecutionResultFlags) GetKernelTimeLimitHitPost() bool {
	if x != nil {
		return x.xxx_hidden_KernelTimeLimitHitPost
	}
	return false
}

func (x *ExecutionResultFlags) GetWallTimeLimitHit() bool {
	if x != nil {
		return x.xxx_hidden_WallTimeLimitHit
	}
	return false
}

func (x *ExecutionResultFlags) SetKilled(v bool) {
	x.xxx_hidden_Killed = v
}

func (x *ExecutionResultFlags) SetTimeLimitHit(v bool) {
	x.xxx_hidden_TimeLimitHit = v
}

func (x *ExecutionResultFlags) SetMemoryLimitHit(v bool) {
	x.xxx_hidden_MemoryLimitHit = v
}

func (x *ExecutionResultFlags) SetInactive(v bool) {
	x.xxx_hidden_Inactive = v
}

func (x *ExecutionResultFlags) SetStdoutOverflow(v bool) {
	x.xxx_hidden_StdoutOverflow = v
}

func (x *ExecutionResultFlags) SetStderrOverflow(v bool) {
	x.xxx_hidden_StderrOverflow = v
}

func (x *ExecutionResultFlags) SetStdpipeTimeout(v bool) {
	x.xxx_hidden_StdpipeTimeout = v
}

func (x *ExecutionResultFlags) SetTimeLimitHitPost(v bool) {
	x.xxx_hidden_TimeLimitHitPost = v
}

func (x *ExecutionResultFlags) SetMemoryLimitHitPost(v bool) {
	x.xxx_hidden_MemoryLimitHitPost = v
}

func (x *ExecutionResultFlags) SetProcessLimitHit(v bool) {
	x.xxx_hidden_ProcessLimitHit = v
}

func (x *ExecutionResultFlags) SetStoppedBySignal(v bool) {
	x.xxx_hidden_StoppedBySignal = v
}

func (x *ExecutionResultFlags) SetKilledBySignal(v bool) {
	x.xxx_hidden_KilledBySignal = v
}

func (x *ExecutionResultFlags) SetKernelTimeLimitHit(v bool) {
	x.xxx_hidden_KernelTimeLimitHit = v
}

func (x *ExecutionResultFlags) SetKernelTimeLimitHitPost(v bool) {
	x.xxx_hidden_KernelTimeLimitHitPost = v
}

func (x *ExecutionResultFlags) SetWallTimeLimitHit(v bool) {
	x.xxx_hidden_WallTimeLimitHit = v
}

type ExecutionResultFlags_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Killed                 bool
	TimeLimitHit           bool
	MemoryLimitHit         bool
	Inactive               bool
	StdoutOverflow         bool
	StderrOverflow         bool
	StdpipeTimeout         bool
	TimeLimitHitPost       bool
	MemoryLimitHitPost     bool
	ProcessLimitHit        bool
	StoppedBySignal        bool
	KilledBySignal         bool
	KernelTimeLimitHit     bool
	KernelTimeLimitHitPost bool
	WallTimeLimitHit       bool
}

func (b0 ExecutionResultFlags_builder) Build() *ExecutionResultFlags {
	m0 := &ExecutionResultFlags{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Killed = b.Killed
	x.xxx_hidden_TimeLimitHit = b.TimeLimitHit
	x.xxx_hidden_MemoryLimitHit = b.MemoryLimitHit
	x.xxx_hidden_Inactive = b.Inactive
	x.xxx_hidden_StdoutOverflow = b.StdoutOverflow
	x.xxx_hidden_StderrOverflow = b.StderrOverflow
	x.xxx_hidden_StdpipeTimeout = b.StdpipeTimeout
	x.xxx_hidden_TimeLimitHitPost = b.TimeLimitHitPost
	x.xxx_hidden_MemoryLimitHitPost = b.MemoryLimitHitPost
	x.xxx_hidden_ProcessLimitHit = b.ProcessLimitHit
	x.xxx_hidden_StoppedBySignal = b.StoppedBySignal
	x.xxx_hidden_KilledBySignal = b.KilledBySignal
	x.xxx_hidden_KernelTimeLimitHit = b.KernelTimeLimitHit
	x.xxx_hidden_KernelTimeLimitHitPost = b.KernelTimeLimitHitPost
	x.xxx_hidden_WallTimeLimitHit = b.WallTimeLimitHit
	return m0
}

type ExecutionResultTime struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserTimeMicros   uint64                 `protobuf:"varint,1,opt,name=user_time_micros,json=userTimeMicros"`
	xxx_hidden_KernelTimeMicros uint64                 `protobuf:"varint,2,opt,name=kernel_time_micros,json=kernelTimeMicros"`
	xxx_hidden_WallTimeMicros   uint64                 `protobuf:"varint,3,opt,name=wall_time_micros,json=wallTimeMicros"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ExecutionResultTime) Reset() {
	*x = ExecutionResultTime{}
	mi := &file_Execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResultTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResultTime) ProtoMessage() {}

func (x *ExecutionResultTime) ProtoReflect() protoreflect.Message {
	mi := &file_Execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExecutionResultTime) GetUserTimeMicros() uint64 {
	if x != nil {
		return x.xxx_hidden_UserTimeMicros
	}
	return 0
}

func (x *ExecutionResultTime) GetKernelTimeMicros() uint64 {
	if x != nil {
		return x.xxx_hidden_KernelTimeMicros
	}
	return 0
}

func (x *ExecutionResultTime) GetWallTimeMicros() uint64 {
	if x != nil {
		return x.xxx_hidden_WallTimeMicros
	}
	return 0
}

func (x *ExecutionResultTime) SetUserTimeMicros(v uint64) {
	x.xxx_hidden_UserTimeMicros = v
}

func (x *ExecutionResultTime) SetKernelTimeMicros(v uint64) {
	x.xxx_hidden_KernelTimeMicros = v
}

func (x *ExecutionResultTime) SetWallTimeMicros(v uint64) {
	x.xxx_hidden_WallTimeMicros = v
}

type ExecutionResultTime_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserTimeMicros   uint64
	KernelTimeMicros uint64
	WallTimeMicros   uint64
}

func (b0 ExecutionResultTime_builder) Build() *ExecutionResultTime {
	m0 := &ExecutionResultTime{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UserTimeMicros = b.UserTimeMicros
	x.xxx_hidden_KernelTimeMicros = b.KernelTimeMicros
	x.xxx_hidden_WallTimeMicros = b.WallTimeMicros
	return m0
}

var File_Execution_proto protoreflect.FileDescriptor

const file_Execution_proto_rawDesc = "" +
	"\n" +
	"\x0fExecution.proto\x12\x0fcontester.proto\x1a!google/protobuf/go_features.proto\x1a\vBlobs.proto\"\xde\x01\n" +
	"\x12RedirectParameters\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\bR\x06memory\x12-\n" +
	"\x06buffer\x18\x03 \x01(\v2\x15.contester.proto.BlobR\x06buffer\x12'\n" +
	"\x0fremote_filename\x18\x04 \x01(\tR\x0eremoteFilename\x12<\n" +
	"\x1aremote_authorization_token\x18\x05 \x01(\tR\x18remoteAuthorizationToken\"\x97\x05\n" +
	"\x14ExecutionResultFlags\x12\x16\n" +
	"\x06killed\x18\x01 \x01(\bR\x06killed\x12$\n" +
	"\x0etime_limit_hit\x18\x02 \x01(\bR\ftimeLimitHit\x12(\n" +
	"\x10memory_limit_hit\x18\x03 \x01(\bR\x0ememoryLimitHit\x12\x1a\n" +
	"\binactive\x18\x04 \x01(\bR\binactive\x12'\n" +
	"\x0fstdout_overflow\x18\x06 \x01(\bR\x0estdoutOverflow\x12'\n" +
	"\x0fstderr_overflow\x18\a \x01(\bR\x0estderrOverflow\x12'\n" +
	"\x0fstdpipe_timeout\x18\b \x01(\bR\x0estdpipeTimeout\x12-\n" +
	"\x13time_limit_hit_post\x18\t \x01(\bR\x10timeLimitHitPost\x121\n" +
	"\x15memory_limit_hit_post\x18\n" +
	" \x01(\bR\x12memoryLimitHitPost\x12*\n" +
	"\x11process_limit_hit\x18\v \x01(\bR\x0fprocessLimitHit\x12*\n" +
	"\x11stopped_by_signal\x18\f \x01(\bR\x0fstoppedBySignal\x12(\n" +
	"\x10killed_by_signal\x18\r \x01(\bR\x0ekilledBySignal\x121\n" +
	"\x15kernel_time_limit_hit\x18\x0e \x01(\bR\x12kernelTimeLimitHit\x12:\n" +
	"\x1akernel_time_limit_hit_post\x18\x0f \x01(\bR\x16kernelTimeLimitHitPost\x12-\n" +
	"\x13wall_time_limit_hit\x18\x10 \x01(\bR\x10wallTimeLimitHit\"\x97\x01\n" +
	"\x13ExecutionResultTime\x12(\n" +
	"\x10user_time_micros\x18\x01 \x01(\x04R\x0euserTimeMicros\x12,\n" +
	"\x12kernel_time_micros\x18\x02 \x01(\x04R\x10kernelTimeMicros\x12(\n" +
	"\x10wall_time_micros\x18\x03 \x01(\x04R\x0ewallTimeMicrosB[\n" +
	"\x1corg.stingray.contester.protoZ+github.com/contester/runlib/contester_proto\x92\x03\r\xd2>\x02\x10\x02\b\x02\x10\x01 \x020\x01b\beditionsp\xe8\a"

var file_Execution_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Execution_proto_goTypes = []any{
	(*RedirectParameters)(nil),   // 0: contester.proto.RedirectParameters
	(*ExecutionResultFlags)(nil), // 1: contester.proto.ExecutionResultFlags
	(*ExecutionResultTime)(nil),  // 2: contester.proto.ExecutionResultTime
	(*Blob)(nil),                 // 3: contester.proto.Blob
}
var file_Execution_proto_depIdxs = []int32{
	3, // 0: contester.proto.RedirectParameters.buffer:type_name -> contester.proto.Blob
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Execution_proto_init() }
func file_Execution_proto_init() {
	if File_Execution_proto != nil {
		return
	}
	file_Blobs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Execution_proto_rawDesc), len(file_Execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Execution_proto_goTypes,
		DependencyIndexes: file_Execution_proto_depIdxs,
		MessageInfos:      file_Execution_proto_msgTypes,
	}.Build()
	File_Execution_proto = out.File
	file_Execution_proto_goTypes = nil
	file_Execution_proto_depIdxs = nil
}
