// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: Local.proto

//go:build protoopaque

package contester_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryTypeResponse_Win32BinaryType int32

const (
	BinaryTypeResponse_SCS_32BIT_BINARY BinaryTypeResponse_Win32BinaryType = 0
	BinaryTypeResponse_SCS_DOS_BINARY   BinaryTypeResponse_Win32BinaryType = 1
	BinaryTypeResponse_SCS_WOW_BINARY   BinaryTypeResponse_Win32BinaryType = 2
	BinaryTypeResponse_SCS_PIF_BINARY   BinaryTypeResponse_Win32BinaryType = 3
	BinaryTypeResponse_SCS_POSIX_BINARY BinaryTypeResponse_Win32BinaryType = 4
	BinaryTypeResponse_SCS_OS216_BINARY BinaryTypeResponse_Win32BinaryType = 5
	BinaryTypeResponse_SCS_64BIT_BINARY BinaryTypeResponse_Win32BinaryType = 6
)

// Enum value maps for BinaryTypeResponse_Win32BinaryType.
var (
	BinaryTypeResponse_Win32BinaryType_name = map[int32]string{
		0: "SCS_32BIT_BINARY",
		1: "SCS_DOS_BINARY",
		2: "SCS_WOW_BINARY",
		3: "SCS_PIF_BINARY",
		4: "SCS_POSIX_BINARY",
		5: "SCS_OS216_BINARY",
		6: "SCS_64BIT_BINARY",
	}
	BinaryTypeResponse_Win32BinaryType_value = map[string]int32{
		"SCS_32BIT_BINARY": 0,
		"SCS_DOS_BINARY":   1,
		"SCS_WOW_BINARY":   2,
		"SCS_PIF_BINARY":   3,
		"SCS_POSIX_BINARY": 4,
		"SCS_OS216_BINARY": 5,
		"SCS_64BIT_BINARY": 6,
	}
)

func (x BinaryTypeResponse_Win32BinaryType) Enum() *BinaryTypeResponse_Win32BinaryType {
	p := new(BinaryTypeResponse_Win32BinaryType)
	*p = x
	return p
}

func (x BinaryTypeResponse_Win32BinaryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryTypeResponse_Win32BinaryType) Descriptor() protoreflect.EnumDescriptor {
	return file_Local_proto_enumTypes[0].Descriptor()
}

func (BinaryTypeResponse_Win32BinaryType) Type() protoreflect.EnumType {
	return &file_Local_proto_enumTypes[0]
}

func (x BinaryTypeResponse_Win32BinaryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type LocalEnvironment struct {
	state               protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Empty    bool                          `protobuf:"varint,1,opt,name=empty"`
	xxx_hidden_Variable *[]*LocalEnvironment_Variable `protobuf:"bytes,2,rep,name=variable"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LocalEnvironment) Reset() {
	*x = LocalEnvironment{}
	mi := &file_Local_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalEnvironment) ProtoMessage() {}

func (x *LocalEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalEnvironment) GetEmpty() bool {
	if x != nil {
		return x.xxx_hidden_Empty
	}
	return false
}

func (x *LocalEnvironment) GetVariable() []*LocalEnvironment_Variable {
	if x != nil {
		if x.xxx_hidden_Variable != nil {
			return *x.xxx_hidden_Variable
		}
	}
	return nil
}

func (x *LocalEnvironment) SetEmpty(v bool) {
	x.xxx_hidden_Empty = v
}

func (x *LocalEnvironment) SetVariable(v []*LocalEnvironment_Variable) {
	x.xxx_hidden_Variable = &v
}

type LocalEnvironment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Empty    bool
	Variable []*LocalEnvironment_Variable
}

func (b0 LocalEnvironment_builder) Build() *LocalEnvironment {
	m0 := &LocalEnvironment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Empty = b.Empty
	x.xxx_hidden_Variable = &b.Variable
	return m0
}

type LocalExecutionParameters struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ApplicationName       string                 `protobuf:"bytes,1,opt,name=application_name,json=applicationName"`
	xxx_hidden_CommandLine           string                 `protobuf:"bytes,2,opt,name=command_line,json=commandLine"`
	xxx_hidden_CurrentDirectory      string                 `protobuf:"bytes,3,opt,name=current_directory,json=currentDirectory"`
	xxx_hidden_TimeLimitMicros       uint64                 `protobuf:"varint,4,opt,name=time_limit_micros,json=timeLimitMicros"`
	xxx_hidden_MemoryLimit           uint64                 `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit"`
	xxx_hidden_CheckIdleness         bool                   `protobuf:"varint,6,opt,name=check_idleness,json=checkIdleness"`
	xxx_hidden_Environment           *LocalEnvironment      `protobuf:"bytes,7,opt,name=environment"`
	xxx_hidden_RestrictUi            bool                   `protobuf:"varint,8,opt,name=restrict_ui,json=restrictUi"`
	xxx_hidden_NoJob                 bool                   `protobuf:"varint,9,opt,name=no_job,json=noJob"`
	xxx_hidden_ProcessLimit          uint32                 `protobuf:"varint,10,opt,name=process_limit,json=processLimit"`
	xxx_hidden_KernelTimeLimitMicros uint64                 `protobuf:"varint,19,opt,name=kernel_time_limit_micros,json=kernelTimeLimitMicros"`
	xxx_hidden_WallTimeLimitMicros   uint64                 `protobuf:"varint,20,opt,name=wall_time_limit_micros,json=wallTimeLimitMicros"`
	xxx_hidden_StdIn                 *RedirectParameters    `protobuf:"bytes,12,opt,name=std_in,json=stdIn"`
	xxx_hidden_StdOut                *RedirectParameters    `protobuf:"bytes,13,opt,name=std_out,json=stdOut"`
	xxx_hidden_StdErr                *RedirectParameters    `protobuf:"bytes,14,opt,name=std_err,json=stdErr"`
	xxx_hidden_CommandLineParameters []string               `protobuf:"bytes,16,rep,name=command_line_parameters,json=commandLineParameters"`
	xxx_hidden_SandboxId             string                 `protobuf:"bytes,17,opt,name=sandbox_id,json=sandboxId"`
	xxx_hidden_JoinStdoutStderr      bool                   `protobuf:"varint,18,opt,name=join_stdout_stderr,json=joinStdoutStderr"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *LocalExecutionParameters) Reset() {
	*x = LocalExecutionParameters{}
	mi := &file_Local_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExecutionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecutionParameters) ProtoMessage() {}

func (x *LocalExecutionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalExecutionParameters) GetApplicationName() string {
	if x != nil {
		return x.xxx_hidden_ApplicationName
	}
	return ""
}

func (x *LocalExecutionParameters) GetCommandLine() string {
	if x != nil {
		return x.xxx_hidden_CommandLine
	}
	return ""
}

func (x *LocalExecutionParameters) GetCurrentDirectory() string {
	if x != nil {
		return x.xxx_hidden_CurrentDirectory
	}
	return ""
}

func (x *LocalExecutionParameters) GetTimeLimitMicros() uint64 {
	if x != nil {
		return x.xxx_hidden_TimeLimitMicros
	}
	return 0
}

func (x *LocalExecutionParameters) GetMemoryLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_MemoryLimit
	}
	return 0
}

func (x *LocalExecutionParameters) GetCheckIdleness() bool {
	if x != nil {
		return x.xxx_hidden_CheckIdleness
	}
	return false
}

func (x *LocalExecutionParameters) GetEnvironment() *LocalEnvironment {
	if x != nil {
		return x.xxx_hidden_Environment
	}
	return nil
}

func (x *LocalExecutionParameters) GetRestrictUi() bool {
	if x != nil {
		return x.xxx_hidden_RestrictUi
	}
	return false
}

func (x *LocalExecutionParameters) GetNoJob() bool {
	if x != nil {
		return x.xxx_hidden_NoJob
	}
	return false
}

func (x *LocalExecutionParameters) GetProcessLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_ProcessLimit
	}
	return 0
}

func (x *LocalExecutionParameters) GetKernelTimeLimitMicros() uint64 {
	if x != nil {
		return x.xxx_hidden_KernelTimeLimitMicros
	}
	return 0
}

func (x *LocalExecutionParameters) GetWallTimeLimitMicros() uint64 {
	if x != nil {
		return x.xxx_hidden_WallTimeLimitMicros
	}
	return 0
}

func (x *LocalExecutionParameters) GetStdIn() *RedirectParameters {
	if x != nil {
		return x.xxx_hidden_StdIn
	}
	return nil
}

func (x *LocalExecutionParameters) GetStdOut() *RedirectParameters {
	if x != nil {
		return x.xxx_hidden_StdOut
	}
	return nil
}

func (x *LocalExecutionParameters) GetStdErr() *RedirectParameters {
	if x != nil {
		return x.xxx_hidden_StdErr
	}
	return nil
}

func (x *LocalExecutionParameters) GetCommandLineParameters() []string {
	if x != nil {
		return x.xxx_hidden_CommandLineParameters
	}
	return nil
}

func (x *LocalExecutionParameters) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *LocalExecutionParameters) GetJoinStdoutStderr() bool {
	if x != nil {
		return x.xxx_hidden_JoinStdoutStderr
	}
	return false
}

func (x *LocalExecutionParameters) SetApplicationName(v string) {
	x.xxx_hidden_ApplicationName = v
}

func (x *LocalExecutionParameters) SetCommandLine(v string) {
	x.xxx_hidden_CommandLine = v
}

func (x *LocalExecutionParameters) SetCurrentDirectory(v string) {
	x.xxx_hidden_CurrentDirectory = v
}

func (x *LocalExecutionParameters) SetTimeLimitMicros(v uint64) {
	x.xxx_hidden_TimeLimitMicros = v
}

func (x *LocalExecutionParameters) SetMemoryLimit(v uint64) {
	x.xxx_hidden_MemoryLimit = v
}

func (x *LocalExecutionParameters) SetCheckIdleness(v bool) {
	x.xxx_hidden_CheckIdleness = v
}

func (x *LocalExecutionParameters) SetEnvironment(v *LocalEnvironment) {
	x.xxx_hidden_Environment = v
}

func (x *LocalExecutionParameters) SetRestrictUi(v bool) {
	x.xxx_hidden_RestrictUi = v
}

func (x *LocalExecutionParameters) SetNoJob(v bool) {
	x.xxx_hidden_NoJob = v
}

func (x *LocalExecutionParameters) SetProcessLimit(v uint32) {
	x.xxx_hidden_ProcessLimit = v
}

func (x *LocalExecutionParameters) SetKernelTimeLimitMicros(v uint64) {
	x.xxx_hidden_KernelTimeLimitMicros = v
}

func (x *LocalExecutionParameters) SetWallTimeLimitMicros(v uint64) {
	x.xxx_hidden_WallTimeLimitMicros = v
}

func (x *LocalExecutionParameters) SetStdIn(v *RedirectParameters) {
	x.xxx_hidden_StdIn = v
}

func (x *LocalExecutionParameters) SetStdOut(v *RedirectParameters) {
	x.xxx_hidden_StdOut = v
}

func (x *LocalExecutionParameters) SetStdErr(v *RedirectParameters) {
	x.xxx_hidden_StdErr = v
}

func (x *LocalExecutionParameters) SetCommandLineParameters(v []string) {
	x.xxx_hidden_CommandLineParameters = v
}

func (x *LocalExecutionParameters) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

func (x *LocalExecutionParameters) SetJoinStdoutStderr(v bool) {
	x.xxx_hidden_JoinStdoutStderr = v
}

func (x *LocalExecutionParameters) HasEnvironment() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Environment != nil
}

func (x *LocalExecutionParameters) HasStdIn() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdIn != nil
}

func (x *LocalExecutionParameters) HasStdOut() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdOut != nil
}

func (x *LocalExecutionParameters) HasStdErr() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdErr != nil
}

func (x *LocalExecutionParameters) ClearEnvironment() {
	x.xxx_hidden_Environment = nil
}

func (x *LocalExecutionParameters) ClearStdIn() {
	x.xxx_hidden_StdIn = nil
}

func (x *LocalExecutionParameters) ClearStdOut() {
	x.xxx_hidden_StdOut = nil
}

func (x *LocalExecutionParameters) ClearStdErr() {
	x.xxx_hidden_StdErr = nil
}

type LocalExecutionParameters_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ApplicationName       string
	CommandLine           string
	CurrentDirectory      string
	TimeLimitMicros       uint64
	MemoryLimit           uint64
	CheckIdleness         bool
	Environment           *LocalEnvironment
	RestrictUi            bool
	NoJob                 bool
	ProcessLimit          uint32
	KernelTimeLimitMicros uint64
	WallTimeLimitMicros   uint64
	StdIn                 *RedirectParameters
	StdOut                *RedirectParameters
	StdErr                *RedirectParameters
	CommandLineParameters []string
	SandboxId             string
	JoinStdoutStderr      bool
}

func (b0 LocalExecutionParameters_builder) Build() *LocalExecutionParameters {
	m0 := &LocalExecutionParameters{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ApplicationName = b.ApplicationName
	x.xxx_hidden_CommandLine = b.CommandLine
	x.xxx_hidden_CurrentDirectory = b.CurrentDirectory
	x.xxx_hidden_TimeLimitMicros = b.TimeLimitMicros
	x.xxx_hidden_MemoryLimit = b.MemoryLimit
	x.xxx_hidden_CheckIdleness = b.CheckIdleness
	x.xxx_hidden_Environment = b.Environment
	x.xxx_hidden_RestrictUi = b.RestrictUi
	x.xxx_hidden_NoJob = b.NoJob
	x.xxx_hidden_ProcessLimit = b.ProcessLimit
	x.xxx_hidden_KernelTimeLimitMicros = b.KernelTimeLimitMicros
	x.xxx_hidden_WallTimeLimitMicros = b.WallTimeLimitMicros
	x.xxx_hidden_StdIn = b.StdIn
	x.xxx_hidden_StdOut = b.StdOut
	x.xxx_hidden_StdErr = b.StdErr
	x.xxx_hidden_CommandLineParameters = b.CommandLineParameters
	x.xxx_hidden_SandboxId = b.SandboxId
	x.xxx_hidden_JoinStdoutStderr = b.JoinStdoutStderr
	return m0
}

type LocalExecuteConnected struct {
	state             protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_First  *LocalExecutionParameters `protobuf:"bytes,1,opt,name=first"`
	xxx_hidden_Second *LocalExecutionParameters `protobuf:"bytes,2,opt,name=second"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocalExecuteConnected) Reset() {
	*x = LocalExecuteConnected{}
	mi := &file_Local_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExecuteConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecuteConnected) ProtoMessage() {}

func (x *LocalExecuteConnected) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalExecuteConnected) GetFirst() *LocalExecutionParameters {
	if x != nil {
		return x.xxx_hidden_First
	}
	return nil
}

func (x *LocalExecuteConnected) GetSecond() *LocalExecutionParameters {
	if x != nil {
		return x.xxx_hidden_Second
	}
	return nil
}

func (x *LocalExecuteConnected) SetFirst(v *LocalExecutionParameters) {
	x.xxx_hidden_First = v
}

func (x *LocalExecuteConnected) SetSecond(v *LocalExecutionParameters) {
	x.xxx_hidden_Second = v
}

func (x *LocalExecuteConnected) HasFirst() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_First != nil
}

func (x *LocalExecuteConnected) HasSecond() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Second != nil
}

func (x *LocalExecuteConnected) ClearFirst() {
	x.xxx_hidden_First = nil
}

func (x *LocalExecuteConnected) ClearSecond() {
	x.xxx_hidden_Second = nil
}

type LocalExecuteConnected_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	First  *LocalExecutionParameters
	Second *LocalExecutionParameters
}

func (b0 LocalExecuteConnected_builder) Build() *LocalExecuteConnected {
	m0 := &LocalExecuteConnected{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_First = b.First
	x.xxx_hidden_Second = b.Second
	return m0
}

type LocalExecutionResult struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Flags          *ExecutionResultFlags  `protobuf:"bytes,1,opt,name=flags"`
	xxx_hidden_Time           *ExecutionResultTime   `protobuf:"bytes,2,opt,name=time"`
	xxx_hidden_Memory         uint64                 `protobuf:"varint,3,opt,name=memory"`
	xxx_hidden_ReturnCode     uint32                 `protobuf:"varint,4,opt,name=return_code,json=returnCode"`
	xxx_hidden_StdOut         *Blob                  `protobuf:"bytes,5,opt,name=std_out,json=stdOut"`
	xxx_hidden_StdErr         *Blob                  `protobuf:"bytes,6,opt,name=std_err,json=stdErr"`
	xxx_hidden_TotalProcesses uint64                 `protobuf:"varint,7,opt,name=total_processes,json=totalProcesses"`
	xxx_hidden_KillSignal     int32                  `protobuf:"varint,8,opt,name=kill_signal,json=killSignal"`
	xxx_hidden_StopSignal     int32                  `protobuf:"varint,9,opt,name=stop_signal,json=stopSignal"`
	xxx_hidden_Error          string                 `protobuf:"bytes,10,opt,name=error"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LocalExecutionResult) Reset() {
	*x = LocalExecutionResult{}
	mi := &file_Local_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecutionResult) ProtoMessage() {}

func (x *LocalExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalExecutionResult) GetFlags() *ExecutionResultFlags {
	if x != nil {
		return x.xxx_hidden_Flags
	}
	return nil
}

func (x *LocalExecutionResult) GetTime() *ExecutionResultTime {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *LocalExecutionResult) GetMemory() uint64 {
	if x != nil {
		return x.xxx_hidden_Memory
	}
	return 0
}

func (x *LocalExecutionResult) GetReturnCode() uint32 {
	if x != nil {
		return x.xxx_hidden_ReturnCode
	}
	return 0
}

func (x *LocalExecutionResult) GetStdOut() *Blob {
	if x != nil {
		return x.xxx_hidden_StdOut
	}
	return nil
}

func (x *LocalExecutionResult) GetStdErr() *Blob {
	if x != nil {
		return x.xxx_hidden_StdErr
	}
	return nil
}

func (x *LocalExecutionResult) GetTotalProcesses() uint64 {
	if x != nil {
		return x.xxx_hidden_TotalProcesses
	}
	return 0
}

func (x *LocalExecutionResult) GetKillSignal() int32 {
	if x != nil {
		return x.xxx_hidden_KillSignal
	}
	return 0
}

func (x *LocalExecutionResult) GetStopSignal() int32 {
	if x != nil {
		return x.xxx_hidden_StopSignal
	}
	return 0
}

func (x *LocalExecutionResult) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *LocalExecutionResult) SetFlags(v *ExecutionResultFlags) {
	x.xxx_hidden_Flags = v
}

func (x *LocalExecutionResult) SetTime(v *ExecutionResultTime) {
	x.xxx_hidden_Time = v
}

func (x *LocalExecutionResult) SetMemory(v uint64) {
	x.xxx_hidden_Memory = v
}

func (x *LocalExecutionResult) SetReturnCode(v uint32) {
	x.xxx_hidden_ReturnCode = v
}

func (x *LocalExecutionResult) SetStdOut(v *Blob) {
	x.xxx_hidden_StdOut = v
}

func (x *LocalExecutionResult) SetStdErr(v *Blob) {
	x.xxx_hidden_StdErr = v
}

func (x *LocalExecutionResult) SetTotalProcesses(v uint64) {
	x.xxx_hidden_TotalProcesses = v
}

func (x *LocalExecutionResult) SetKillSignal(v int32) {
	x.xxx_hidden_KillSignal = v
}

func (x *LocalExecutionResult) SetStopSignal(v int32) {
	x.xxx_hidden_StopSignal = v
}

func (x *LocalExecutionResult) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *LocalExecutionResult) HasFlags() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Flags != nil
}

func (x *LocalExecutionResult) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *LocalExecutionResult) HasStdOut() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdOut != nil
}

func (x *LocalExecutionResult) HasStdErr() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StdErr != nil
}

func (x *LocalExecutionResult) ClearFlags() {
	x.xxx_hidden_Flags = nil
}

func (x *LocalExecutionResult) ClearTime() {
	x.xxx_hidden_Time = nil
}

func (x *LocalExecutionResult) ClearStdOut() {
	x.xxx_hidden_StdOut = nil
}

func (x *LocalExecutionResult) ClearStdErr() {
	x.xxx_hidden_StdErr = nil
}

type LocalExecutionResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Flags          *ExecutionResultFlags
	Time           *ExecutionResultTime
	Memory         uint64
	ReturnCode     uint32
	StdOut         *Blob
	StdErr         *Blob
	TotalProcesses uint64
	KillSignal     int32
	StopSignal     int32
	Error          string
}

func (b0 LocalExecutionResult_builder) Build() *LocalExecutionResult {
	m0 := &LocalExecutionResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Flags = b.Flags
	x.xxx_hidden_Time = b.Time
	x.xxx_hidden_Memory = b.Memory
	x.xxx_hidden_ReturnCode = b.ReturnCode
	x.xxx_hidden_StdOut = b.StdOut
	x.xxx_hidden_StdErr = b.StdErr
	x.xxx_hidden_TotalProcesses = b.TotalProcesses
	x.xxx_hidden_KillSignal = b.KillSignal
	x.xxx_hidden_StopSignal = b.StopSignal
	x.xxx_hidden_Error = b.Error
	return m0
}

type LocalExecuteConnectedResult struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_First  *LocalExecutionResult  `protobuf:"bytes,1,opt,name=first"`
	xxx_hidden_Second *LocalExecutionResult  `protobuf:"bytes,2,opt,name=second"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocalExecuteConnectedResult) Reset() {
	*x = LocalExecuteConnectedResult{}
	mi := &file_Local_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExecuteConnectedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecuteConnectedResult) ProtoMessage() {}

func (x *LocalExecuteConnectedResult) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalExecuteConnectedResult) GetFirst() *LocalExecutionResult {
	if x != nil {
		return x.xxx_hidden_First
	}
	return nil
}

func (x *LocalExecuteConnectedResult) GetSecond() *LocalExecutionResult {
	if x != nil {
		return x.xxx_hidden_Second
	}
	return nil
}

func (x *LocalExecuteConnectedResult) SetFirst(v *LocalExecutionResult) {
	x.xxx_hidden_First = v
}

func (x *LocalExecuteConnectedResult) SetSecond(v *LocalExecutionResult) {
	x.xxx_hidden_Second = v
}

func (x *LocalExecuteConnectedResult) HasFirst() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_First != nil
}

func (x *LocalExecuteConnectedResult) HasSecond() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Second != nil
}

func (x *LocalExecuteConnectedResult) ClearFirst() {
	x.xxx_hidden_First = nil
}

func (x *LocalExecuteConnectedResult) ClearSecond() {
	x.xxx_hidden_Second = nil
}

type LocalExecuteConnectedResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	First  *LocalExecutionResult
	Second *LocalExecutionResult
}

func (b0 LocalExecuteConnectedResult_builder) Build() *LocalExecuteConnectedResult {
	m0 := &LocalExecuteConnectedResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_First = b.First
	x.xxx_hidden_Second = b.Second
	return m0
}

type LocalExecution struct {
	state                 protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Parameters *LocalExecutionParameters `protobuf:"bytes,1,opt,name=parameters"`
	xxx_hidden_Result     *LocalExecutionResult     `protobuf:"bytes,2,opt,name=result"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LocalExecution) Reset() {
	*x = LocalExecution{}
	mi := &file_Local_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecution) ProtoMessage() {}

func (x *LocalExecution) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalExecution) GetParameters() *LocalExecutionParameters {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *LocalExecution) GetResult() *LocalExecutionResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *LocalExecution) SetParameters(v *LocalExecutionParameters) {
	x.xxx_hidden_Parameters = v
}

func (x *LocalExecution) SetResult(v *LocalExecutionResult) {
	x.xxx_hidden_Result = v
}

func (x *LocalExecution) HasParameters() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parameters != nil
}

func (x *LocalExecution) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *LocalExecution) ClearParameters() {
	x.xxx_hidden_Parameters = nil
}

func (x *LocalExecution) ClearResult() {
	x.xxx_hidden_Result = nil
}

type LocalExecution_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Parameters *LocalExecutionParameters
	Result     *LocalExecutionResult
}

func (b0 LocalExecution_builder) Build() *LocalExecution {
	m0 := &LocalExecution{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Parameters = b.Parameters
	x.xxx_hidden_Result = b.Result
	return m0
}

type BinaryTypeRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pathname string                 `protobuf:"bytes,1,opt,name=pathname"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BinaryTypeRequest) Reset() {
	*x = BinaryTypeRequest{}
	mi := &file_Local_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryTypeRequest) ProtoMessage() {}

func (x *BinaryTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryTypeRequest) GetPathname() string {
	if x != nil {
		return x.xxx_hidden_Pathname
	}
	return ""
}

func (x *BinaryTypeRequest) SetPathname(v string) {
	x.xxx_hidden_Pathname = v
}

type BinaryTypeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pathname string
}

func (b0 BinaryTypeRequest_builder) Build() *BinaryTypeRequest {
	m0 := &BinaryTypeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pathname = b.Pathname
	return m0
}

type BinaryTypeResponse struct {
	state              protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Failure bool                               `protobuf:"varint,1,opt,name=failure"`
	xxx_hidden_Result  BinaryTypeResponse_Win32BinaryType `protobuf:"varint,2,opt,name=result,enum=contester.proto.BinaryTypeResponse_Win32BinaryType"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BinaryTypeResponse) Reset() {
	*x = BinaryTypeResponse{}
	mi := &file_Local_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryTypeResponse) ProtoMessage() {}

func (x *BinaryTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryTypeResponse) GetFailure() bool {
	if x != nil {
		return x.xxx_hidden_Failure
	}
	return false
}

func (x *BinaryTypeResponse) GetResult() BinaryTypeResponse_Win32BinaryType {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return BinaryTypeResponse_SCS_32BIT_BINARY
}

func (x *BinaryTypeResponse) SetFailure(v bool) {
	x.xxx_hidden_Failure = v
}

func (x *BinaryTypeResponse) SetResult(v BinaryTypeResponse_Win32BinaryType) {
	x.xxx_hidden_Result = v
}

type BinaryTypeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Failure bool
	Result  BinaryTypeResponse_Win32BinaryType
}

func (b0 BinaryTypeResponse_builder) Build() *BinaryTypeResponse {
	m0 := &BinaryTypeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Failure = b.Failure
	x.xxx_hidden_Result = b.Result
	return m0
}

type ClearSandboxRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sandbox string                 `protobuf:"bytes,1,opt,name=sandbox"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClearSandboxRequest) Reset() {
	*x = ClearSandboxRequest{}
	mi := &file_Local_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSandboxRequest) ProtoMessage() {}

func (x *ClearSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ClearSandboxRequest) GetSandbox() string {
	if x != nil {
		return x.xxx_hidden_Sandbox
	}
	return ""
}

func (x *ClearSandboxRequest) SetSandbox(v string) {
	x.xxx_hidden_Sandbox = v
}

type ClearSandboxRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sandbox string
}

func (b0 ClearSandboxRequest_builder) Build() *ClearSandboxRequest {
	m0 := &ClearSandboxRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sandbox = b.Sandbox
	return m0
}

type IdentifyRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContesterId string                 `protobuf:"bytes,1,opt,name=contester_id,json=contesterId"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	mi := &file_Local_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentifyRequest) GetContesterId() string {
	if x != nil {
		return x.xxx_hidden_ContesterId
	}
	return ""
}

func (x *IdentifyRequest) SetContesterId(v string) {
	x.xxx_hidden_ContesterId = v
}

type IdentifyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContesterId string
}

func (b0 IdentifyRequest_builder) Build() *IdentifyRequest {
	m0 := &IdentifyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContesterId = b.ContesterId
	return m0
}

type SandboxLocations struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Compile string                 `protobuf:"bytes,1,opt,name=compile"`
	xxx_hidden_Run     string                 `protobuf:"bytes,2,opt,name=run"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxLocations) Reset() {
	*x = SandboxLocations{}
	mi := &file_Local_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxLocations) ProtoMessage() {}

func (x *SandboxLocations) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SandboxLocations) GetCompile() string {
	if x != nil {
		return x.xxx_hidden_Compile
	}
	return ""
}

func (x *SandboxLocations) GetRun() string {
	if x != nil {
		return x.xxx_hidden_Run
	}
	return ""
}

func (x *SandboxLocations) SetCompile(v string) {
	x.xxx_hidden_Compile = v
}

func (x *SandboxLocations) SetRun(v string) {
	x.xxx_hidden_Run = v
}

type SandboxLocations_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Compile string
	Run     string
}

func (b0 SandboxLocations_builder) Build() *SandboxLocations {
	m0 := &SandboxLocations{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Compile = b.Compile
	x.xxx_hidden_Run = b.Run
	return m0
}

type IdentifyResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_InvokerId     string                 `protobuf:"bytes,1,opt,name=invoker_id,json=invokerId"`
	xxx_hidden_Sandboxes     *[]*SandboxLocations   `protobuf:"bytes,2,rep,name=sandboxes"`
	xxx_hidden_Environment   *LocalEnvironment      `protobuf:"bytes,3,opt,name=environment"`
	xxx_hidden_Platform      string                 `protobuf:"bytes,4,opt,name=platform"`
	xxx_hidden_PathSeparator string                 `protobuf:"bytes,5,opt,name=path_separator,json=pathSeparator"`
	xxx_hidden_Disks         []string               `protobuf:"bytes,6,rep,name=disks"`
	xxx_hidden_ProgramFiles  []string               `protobuf:"bytes,7,rep,name=programFiles"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	mi := &file_Local_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IdentifyResponse) GetInvokerId() string {
	if x != nil {
		return x.xxx_hidden_InvokerId
	}
	return ""
}

func (x *IdentifyResponse) GetSandboxes() []*SandboxLocations {
	if x != nil {
		if x.xxx_hidden_Sandboxes != nil {
			return *x.xxx_hidden_Sandboxes
		}
	}
	return nil
}

func (x *IdentifyResponse) GetEnvironment() *LocalEnvironment {
	if x != nil {
		return x.xxx_hidden_Environment
	}
	return nil
}

func (x *IdentifyResponse) GetPlatform() string {
	if x != nil {
		return x.xxx_hidden_Platform
	}
	return ""
}

func (x *IdentifyResponse) GetPathSeparator() string {
	if x != nil {
		return x.xxx_hidden_PathSeparator
	}
	return ""
}

func (x *IdentifyResponse) GetDisks() []string {
	if x != nil {
		return x.xxx_hidden_Disks
	}
	return nil
}

func (x *IdentifyResponse) GetProgramFiles() []string {
	if x != nil {
		return x.xxx_hidden_ProgramFiles
	}
	return nil
}

func (x *IdentifyResponse) SetInvokerId(v string) {
	x.xxx_hidden_InvokerId = v
}

func (x *IdentifyResponse) SetSandboxes(v []*SandboxLocations) {
	x.xxx_hidden_Sandboxes = &v
}

func (x *IdentifyResponse) SetEnvironment(v *LocalEnvironment) {
	x.xxx_hidden_Environment = v
}

func (x *IdentifyResponse) SetPlatform(v string) {
	x.xxx_hidden_Platform = v
}

func (x *IdentifyResponse) SetPathSeparator(v string) {
	x.xxx_hidden_PathSeparator = v
}

func (x *IdentifyResponse) SetDisks(v []string) {
	x.xxx_hidden_Disks = v
}

func (x *IdentifyResponse) SetProgramFiles(v []string) {
	x.xxx_hidden_ProgramFiles = v
}

func (x *IdentifyResponse) HasEnvironment() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Environment != nil
}

func (x *IdentifyResponse) ClearEnvironment() {
	x.xxx_hidden_Environment = nil
}

type IdentifyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	InvokerId     string
	Sandboxes     []*SandboxLocations
	Environment   *LocalEnvironment
	Platform      string
	PathSeparator string
	Disks         []string
	ProgramFiles  []string
}

func (b0 IdentifyResponse_builder) Build() *IdentifyResponse {
	m0 := &IdentifyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_InvokerId = b.InvokerId
	x.xxx_hidden_Sandboxes = &b.Sandboxes
	x.xxx_hidden_Environment = b.Environment
	x.xxx_hidden_Platform = b.Platform
	x.xxx_hidden_PathSeparator = b.PathSeparator
	x.xxx_hidden_Disks = b.Disks
	x.xxx_hidden_ProgramFiles = b.ProgramFiles
	return m0
}

type FileStat struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_IsDirectory bool                   `protobuf:"varint,2,opt,name=is_directory,json=isDirectory"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,3,opt,name=size"`
	xxx_hidden_Checksum    string                 `protobuf:"bytes,4,opt,name=checksum"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileStat) Reset() {
	*x = FileStat{}
	mi := &file_Local_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat) ProtoMessage() {}

func (x *FileStat) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileStat) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *FileStat) GetIsDirectory() bool {
	if x != nil {
		return x.xxx_hidden_IsDirectory
	}
	return false
}

func (x *FileStat) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileStat) GetChecksum() string {
	if x != nil {
		return x.xxx_hidden_Checksum
	}
	return ""
}

func (x *FileStat) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *FileStat) SetIsDirectory(v bool) {
	x.xxx_hidden_IsDirectory = v
}

func (x *FileStat) SetSize(v uint64) {
	x.xxx_hidden_Size = v
}

func (x *FileStat) SetChecksum(v string) {
	x.xxx_hidden_Checksum = v
}

type FileStat_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name        string
	IsDirectory bool
	Size        uint64
	Checksum    string
}

func (b0 FileStat_builder) Build() *FileStat {
	m0 := &FileStat{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_IsDirectory = b.IsDirectory
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_Checksum = b.Checksum
	return m0
}

type StatRequest struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name              []string               `protobuf:"bytes,1,rep,name=name"`
	xxx_hidden_SandboxId         string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId"`
	xxx_hidden_Expand            bool                   `protobuf:"varint,3,opt,name=expand"`
	xxx_hidden_CalculateChecksum bool                   `protobuf:"varint,4,opt,name=calculate_checksum,json=calculateChecksum"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_Local_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StatRequest) GetName() []string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return nil
}

func (x *StatRequest) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *StatRequest) GetExpand() bool {
	if x != nil {
		return x.xxx_hidden_Expand
	}
	return false
}

func (x *StatRequest) GetCalculateChecksum() bool {
	if x != nil {
		return x.xxx_hidden_CalculateChecksum
	}
	return false
}

func (x *StatRequest) SetName(v []string) {
	x.xxx_hidden_Name = v
}

func (x *StatRequest) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

func (x *StatRequest) SetExpand(v bool) {
	x.xxx_hidden_Expand = v
}

func (x *StatRequest) SetCalculateChecksum(v bool) {
	x.xxx_hidden_CalculateChecksum = v
}

type StatRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name              []string
	SandboxId         string
	Expand            bool
	CalculateChecksum bool
}

func (b0 StatRequest_builder) Build() *StatRequest {
	m0 := &StatRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_SandboxId = b.SandboxId
	x.xxx_hidden_Expand = b.Expand
	x.xxx_hidden_CalculateChecksum = b.CalculateChecksum
	return m0
}

type FileStats struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*FileStat           `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FileStats) Reset() {
	*x = FileStats{}
	mi := &file_Local_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStats) ProtoMessage() {}

func (x *FileStats) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileStats) GetEntries() []*FileStat {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *FileStats) SetEntries(v []*FileStat) {
	x.xxx_hidden_Entries = &v
}

type FileStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*FileStat
}

func (b0 FileStats_builder) Build() *FileStats {
	m0 := &FileStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type GetRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_Local_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *GetRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_Local_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type EmptyMessage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 EmptyMessage_builder) Build() *EmptyMessage {
	m0 := &EmptyMessage{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CopyOperation struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocalFileName      string                 `protobuf:"bytes,1,opt,name=local_file_name,json=localFileName"`
	xxx_hidden_RemoteLocation     string                 `protobuf:"bytes,2,opt,name=remote_location,json=remoteLocation"`
	xxx_hidden_Upload             bool                   `protobuf:"varint,3,opt,name=upload"`
	xxx_hidden_Checksum           string                 `protobuf:"bytes,4,opt,name=checksum"`
	xxx_hidden_ModuleType         string                 `protobuf:"bytes,5,opt,name=module_type,json=moduleType"`
	xxx_hidden_AuthorizationToken string                 `protobuf:"bytes,6,opt,name=authorization_token,json=authorizationToken"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CopyOperation) Reset() {
	*x = CopyOperation{}
	mi := &file_Local_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOperation) ProtoMessage() {}

func (x *CopyOperation) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CopyOperation) GetLocalFileName() string {
	if x != nil {
		return x.xxx_hidden_LocalFileName
	}
	return ""
}

func (x *CopyOperation) GetRemoteLocation() string {
	if x != nil {
		return x.xxx_hidden_RemoteLocation
	}
	return ""
}

func (x *CopyOperation) GetUpload() bool {
	if x != nil {
		return x.xxx_hidden_Upload
	}
	return false
}

func (x *CopyOperation) GetChecksum() string {
	if x != nil {
		return x.xxx_hidden_Checksum
	}
	return ""
}

func (x *CopyOperation) GetModuleType() string {
	if x != nil {
		return x.xxx_hidden_ModuleType
	}
	return ""
}

func (x *CopyOperation) GetAuthorizationToken() string {
	if x != nil {
		return x.xxx_hidden_AuthorizationToken
	}
	return ""
}

func (x *CopyOperation) SetLocalFileName(v string) {
	x.xxx_hidden_LocalFileName = v
}

func (x *CopyOperation) SetRemoteLocation(v string) {
	x.xxx_hidden_RemoteLocation = v
}

func (x *CopyOperation) SetUpload(v bool) {
	x.xxx_hidden_Upload = v
}

func (x *CopyOperation) SetChecksum(v string) {
	x.xxx_hidden_Checksum = v
}

func (x *CopyOperation) SetModuleType(v string) {
	x.xxx_hidden_ModuleType = v
}

func (x *CopyOperation) SetAuthorizationToken(v string) {
	x.xxx_hidden_AuthorizationToken = v
}

type CopyOperation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LocalFileName      string
	RemoteLocation     string
	Upload             bool
	Checksum           string
	ModuleType         string
	AuthorizationToken string
}

func (b0 CopyOperation_builder) Build() *CopyOperation {
	m0 := &CopyOperation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LocalFileName = b.LocalFileName
	x.xxx_hidden_RemoteLocation = b.RemoteLocation
	x.xxx_hidden_Upload = b.Upload
	x.xxx_hidden_Checksum = b.Checksum
	x.xxx_hidden_ModuleType = b.ModuleType
	x.xxx_hidden_AuthorizationToken = b.AuthorizationToken
	return m0
}

type CopyOperations struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries   *[]*CopyOperation      `protobuf:"bytes,1,rep,name=entries"`
	xxx_hidden_SandboxId string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CopyOperations) Reset() {
	*x = CopyOperations{}
	mi := &file_Local_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOperations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOperations) ProtoMessage() {}

func (x *CopyOperations) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CopyOperations) GetEntries() []*CopyOperation {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *CopyOperations) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *CopyOperations) SetEntries(v []*CopyOperation) {
	x.xxx_hidden_Entries = &v
}

func (x *CopyOperations) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

type CopyOperations_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries   []*CopyOperation
	SandboxId string
}

func (b0 CopyOperations_builder) Build() *CopyOperations {
	m0 := &CopyOperations{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	x.xxx_hidden_SandboxId = b.SandboxId
	return m0
}

type NamePair struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source      string                 `protobuf:"bytes,1,opt,name=source"`
	xxx_hidden_Destination string                 `protobuf:"bytes,2,opt,name=destination"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NamePair) Reset() {
	*x = NamePair{}
	mi := &file_Local_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamePair) ProtoMessage() {}

func (x *NamePair) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NamePair) GetSource() string {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return ""
}

func (x *NamePair) GetDestination() string {
	if x != nil {
		return x.xxx_hidden_Destination
	}
	return ""
}

func (x *NamePair) SetSource(v string) {
	x.xxx_hidden_Source = v
}

func (x *NamePair) SetDestination(v string) {
	x.xxx_hidden_Destination = v
}

type NamePair_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Source      string
	Destination string
}

func (b0 NamePair_builder) Build() *NamePair {
	m0 := &NamePair{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Destination = b.Destination
	return m0
}

type RepeatedNamePairEntries struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries   *[]*NamePair           `protobuf:"bytes,1,rep,name=entries"`
	xxx_hidden_SandboxId string                 `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RepeatedNamePairEntries) Reset() {
	*x = RepeatedNamePairEntries{}
	mi := &file_Local_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedNamePairEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedNamePairEntries) ProtoMessage() {}

func (x *RepeatedNamePairEntries) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepeatedNamePairEntries) GetEntries() []*NamePair {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *RepeatedNamePairEntries) GetSandboxId() string {
	if x != nil {
		return x.xxx_hidden_SandboxId
	}
	return ""
}

func (x *RepeatedNamePairEntries) SetEntries(v []*NamePair) {
	x.xxx_hidden_Entries = &v
}

func (x *RepeatedNamePairEntries) SetSandboxId(v string) {
	x.xxx_hidden_SandboxId = v
}

type RepeatedNamePairEntries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries   []*NamePair
	SandboxId string
}

func (b0 RepeatedNamePairEntries_builder) Build() *RepeatedNamePairEntries {
	m0 := &RepeatedNamePairEntries{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	x.xxx_hidden_SandboxId = b.SandboxId
	return m0
}

type RepeatedStringEntries struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries []string               `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RepeatedStringEntries) Reset() {
	*x = RepeatedStringEntries{}
	mi := &file_Local_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedStringEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedStringEntries) ProtoMessage() {}

func (x *RepeatedStringEntries) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RepeatedStringEntries) GetEntries() []string {
	if x != nil {
		return x.xxx_hidden_Entries
	}
	return nil
}

func (x *RepeatedStringEntries) SetEntries(v []string) {
	x.xxx_hidden_Entries = v
}

type RepeatedStringEntries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []string
}

func (b0 RepeatedStringEntries_builder) Build() *RepeatedStringEntries {
	m0 := &RepeatedStringEntries{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = b.Entries
	return m0
}

type LocalEnvironment_Variable struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name   string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Value  string                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Expand bool                   `protobuf:"varint,3,opt,name=expand"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocalEnvironment_Variable) Reset() {
	*x = LocalEnvironment_Variable{}
	mi := &file_Local_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalEnvironment_Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalEnvironment_Variable) ProtoMessage() {}

func (x *LocalEnvironment_Variable) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LocalEnvironment_Variable) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *LocalEnvironment_Variable) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *LocalEnvironment_Variable) GetExpand() bool {
	if x != nil {
		return x.xxx_hidden_Expand
	}
	return false
}

func (x *LocalEnvironment_Variable) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *LocalEnvironment_Variable) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *LocalEnvironment_Variable) SetExpand(v bool) {
	x.xxx_hidden_Expand = v
}

type LocalEnvironment_Variable_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name   string
	Value  string
	Expand bool
}

func (b0 LocalEnvironment_Variable_builder) Build() *LocalEnvironment_Variable {
	m0 := &LocalEnvironment_Variable{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Expand = b.Expand
	return m0
}

var File_Local_proto protoreflect.FileDescriptor

const file_Local_proto_rawDesc = "" +
	"\n" +
	"\vLocal.proto\x12\x0fcontester.proto\x1a!google/protobuf/go_features.proto\x1a\vBlobs.proto\x1a\x0fExecution.proto\"\xbe\x01\n" +
	"\x10LocalEnvironment\x12\x14\n" +
	"\x05empty\x18\x01 \x01(\bR\x05empty\x12F\n" +
	"\bvariable\x18\x02 \x03(\v2*.contester.proto.LocalEnvironment.VariableR\bvariable\x1aL\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06expand\x18\x03 \x01(\bR\x06expand\"\xd8\x06\n" +
	"\x18LocalExecutionParameters\x12)\n" +
	"\x10application_name\x18\x01 \x01(\tR\x0fapplicationName\x12!\n" +
	"\fcommand_line\x18\x02 \x01(\tR\vcommandLine\x12+\n" +
	"\x11current_directory\x18\x03 \x01(\tR\x10currentDirectory\x12*\n" +
	"\x11time_limit_micros\x18\x04 \x01(\x04R\x0ftimeLimitMicros\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x04R\vmemoryLimit\x12%\n" +
	"\x0echeck_idleness\x18\x06 \x01(\bR\rcheckIdleness\x12C\n" +
	"\venvironment\x18\a \x01(\v2!.contester.proto.LocalEnvironmentR\venvironment\x12\x1f\n" +
	"\vrestrict_ui\x18\b \x01(\bR\n" +
	"restrictUi\x12\x15\n" +
	"\x06no_job\x18\t \x01(\bR\x05noJob\x12#\n" +
	"\rprocess_limit\x18\n" +
	" \x01(\rR\fprocessLimit\x127\n" +
	"\x18kernel_time_limit_micros\x18\x13 \x01(\x04R\x15kernelTimeLimitMicros\x123\n" +
	"\x16wall_time_limit_micros\x18\x14 \x01(\x04R\x13wallTimeLimitMicros\x12:\n" +
	"\x06std_in\x18\f \x01(\v2#.contester.proto.RedirectParametersR\x05stdIn\x12<\n" +
	"\astd_out\x18\r \x01(\v2#.contester.proto.RedirectParametersR\x06stdOut\x12<\n" +
	"\astd_err\x18\x0e \x01(\v2#.contester.proto.RedirectParametersR\x06stdErr\x126\n" +
	"\x17command_line_parameters\x18\x10 \x03(\tR\x15commandLineParameters\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x11 \x01(\tR\tsandboxId\x12,\n" +
	"\x12join_stdout_stderr\x18\x12 \x01(\bR\x10joinStdoutStderr\"\x9b\x01\n" +
	"\x15LocalExecuteConnected\x12?\n" +
	"\x05first\x18\x01 \x01(\v2).contester.proto.LocalExecutionParametersR\x05first\x12A\n" +
	"\x06second\x18\x02 \x01(\v2).contester.proto.LocalExecutionParametersR\x06second\"\xa7\x03\n" +
	"\x14LocalExecutionResult\x12;\n" +
	"\x05flags\x18\x01 \x01(\v2%.contester.proto.ExecutionResultFlagsR\x05flags\x128\n" +
	"\x04time\x18\x02 \x01(\v2$.contester.proto.ExecutionResultTimeR\x04time\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x04R\x06memory\x12\x1f\n" +
	"\vreturn_code\x18\x04 \x01(\rR\n" +
	"returnCode\x12.\n" +
	"\astd_out\x18\x05 \x01(\v2\x15.contester.proto.BlobR\x06stdOut\x12.\n" +
	"\astd_err\x18\x06 \x01(\v2\x15.contester.proto.BlobR\x06stdErr\x12'\n" +
	"\x0ftotal_processes\x18\a \x01(\x04R\x0etotalProcesses\x12\x1f\n" +
	"\vkill_signal\x18\b \x01(\x05R\n" +
	"killSignal\x12\x1f\n" +
	"\vstop_signal\x18\t \x01(\x05R\n" +
	"stopSignal\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\x99\x01\n" +
	"\x1bLocalExecuteConnectedResult\x12;\n" +
	"\x05first\x18\x01 \x01(\v2%.contester.proto.LocalExecutionResultR\x05first\x12=\n" +
	"\x06second\x18\x02 \x01(\v2%.contester.proto.LocalExecutionResultR\x06second\"\x9a\x01\n" +
	"\x0eLocalExecution\x12I\n" +
	"\n" +
	"parameters\x18\x01 \x01(\v2).contester.proto.LocalExecutionParametersR\n" +
	"parameters\x12=\n" +
	"\x06result\x18\x02 \x01(\v2%.contester.proto.LocalExecutionResultR\x06result\"/\n" +
	"\x11BinaryTypeRequest\x12\x1a\n" +
	"\bpathname\x18\x01 \x01(\tR\bpathname\"\xa3\x02\n" +
	"\x12BinaryTypeResponse\x12\x18\n" +
	"\afailure\x18\x01 \x01(\bR\afailure\x12K\n" +
	"\x06result\x18\x02 \x01(\x0e23.contester.proto.BinaryTypeResponse.Win32BinaryTypeR\x06result\"\xa5\x01\n" +
	"\x0fWin32BinaryType\x12\x14\n" +
	"\x10SCS_32BIT_BINARY\x10\x00\x12\x12\n" +
	"\x0eSCS_DOS_BINARY\x10\x01\x12\x12\n" +
	"\x0eSCS_WOW_BINARY\x10\x02\x12\x12\n" +
	"\x0eSCS_PIF_BINARY\x10\x03\x12\x14\n" +
	"\x10SCS_POSIX_BINARY\x10\x04\x12\x14\n" +
	"\x10SCS_OS216_BINARY\x10\x05\x12\x14\n" +
	"\x10SCS_64BIT_BINARY\x10\x06\"/\n" +
	"\x13ClearSandboxRequest\x12\x18\n" +
	"\asandbox\x18\x01 \x01(\tR\asandbox\"4\n" +
	"\x0fIdentifyRequest\x12!\n" +
	"\fcontester_id\x18\x01 \x01(\tR\vcontesterId\">\n" +
	"\x10SandboxLocations\x12\x18\n" +
	"\acompile\x18\x01 \x01(\tR\acompile\x12\x10\n" +
	"\x03run\x18\x02 \x01(\tR\x03run\"\xb4\x02\n" +
	"\x10IdentifyResponse\x12\x1d\n" +
	"\n" +
	"invoker_id\x18\x01 \x01(\tR\tinvokerId\x12?\n" +
	"\tsandboxes\x18\x02 \x03(\v2!.contester.proto.SandboxLocationsR\tsandboxes\x12C\n" +
	"\venvironment\x18\x03 \x01(\v2!.contester.proto.LocalEnvironmentR\venvironment\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12%\n" +
	"\x0epath_separator\x18\x05 \x01(\tR\rpathSeparator\x12\x14\n" +
	"\x05disks\x18\x06 \x03(\tR\x05disks\x12\"\n" +
	"\fprogramFiles\x18\a \x03(\tR\fprogramFiles\"q\n" +
	"\bFileStat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_directory\x18\x02 \x01(\bR\visDirectory\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"\x87\x01\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04name\x18\x01 \x03(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\x12\x16\n" +
	"\x06expand\x18\x03 \x01(\bR\x06expand\x12-\n" +
	"\x12calculate_checksum\x18\x04 \x01(\bR\x11calculateChecksum\"@\n" +
	"\tFileStats\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.contester.proto.FileStatR\aentries\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x0e\n" +
	"\fEmptyMessage\"\xe6\x01\n" +
	"\rCopyOperation\x12&\n" +
	"\x0flocal_file_name\x18\x01 \x01(\tR\rlocalFileName\x12'\n" +
	"\x0fremote_location\x18\x02 \x01(\tR\x0eremoteLocation\x12\x16\n" +
	"\x06upload\x18\x03 \x01(\bR\x06upload\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\x12\x1f\n" +
	"\vmodule_type\x18\x05 \x01(\tR\n" +
	"moduleType\x12/\n" +
	"\x13authorization_token\x18\x06 \x01(\tR\x12authorizationToken\"i\n" +
	"\x0eCopyOperations\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.contester.proto.CopyOperationR\aentries\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\"D\n" +
	"\bNamePair\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"m\n" +
	"\x17RepeatedNamePairEntries\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.contester.proto.NamePairR\aentries\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x02 \x01(\tR\tsandboxId\"1\n" +
	"\x15RepeatedStringEntries\x12\x18\n" +
	"\aentries\x18\x01 \x03(\tR\aentriesB[\n" +
	"\x1corg.stingray.contester.protoZ+github.com/contester/runlib/contester_proto\x92\x03\r\xd2>\x02\x10\x02\b\x02\x10\x01 \x020\x01b\beditionsp\xe8\a"

var file_Local_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Local_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_Local_proto_goTypes = []any{
	(BinaryTypeResponse_Win32BinaryType)(0), // 0: contester.proto.BinaryTypeResponse.Win32BinaryType
	(*LocalEnvironment)(nil),                // 1: contester.proto.LocalEnvironment
	(*LocalExecutionParameters)(nil),        // 2: contester.proto.LocalExecutionParameters
	(*LocalExecuteConnected)(nil),           // 3: contester.proto.LocalExecuteConnected
	(*LocalExecutionResult)(nil),            // 4: contester.proto.LocalExecutionResult
	(*LocalExecuteConnectedResult)(nil),     // 5: contester.proto.LocalExecuteConnectedResult
	(*LocalExecution)(nil),                  // 6: contester.proto.LocalExecution
	(*BinaryTypeRequest)(nil),               // 7: contester.proto.BinaryTypeRequest
	(*BinaryTypeResponse)(nil),              // 8: contester.proto.BinaryTypeResponse
	(*ClearSandboxRequest)(nil),             // 9: contester.proto.ClearSandboxRequest
	(*IdentifyRequest)(nil),                 // 10: contester.proto.IdentifyRequest
	(*SandboxLocations)(nil),                // 11: contester.proto.SandboxLocations
	(*IdentifyResponse)(nil),                // 12: contester.proto.IdentifyResponse
	(*FileStat)(nil),                        // 13: contester.proto.FileStat
	(*StatRequest)(nil),                     // 14: contester.proto.StatRequest
	(*FileStats)(nil),                       // 15: contester.proto.FileStats
	(*GetRequest)(nil),                      // 16: contester.proto.GetRequest
	(*EmptyMessage)(nil),                    // 17: contester.proto.EmptyMessage
	(*CopyOperation)(nil),                   // 18: contester.proto.CopyOperation
	(*CopyOperations)(nil),                  // 19: contester.proto.CopyOperations
	(*NamePair)(nil),                        // 20: contester.proto.NamePair
	(*RepeatedNamePairEntries)(nil),         // 21: contester.proto.RepeatedNamePairEntries
	(*RepeatedStringEntries)(nil),           // 22: contester.proto.RepeatedStringEntries
	(*LocalEnvironment_Variable)(nil),       // 23: contester.proto.LocalEnvironment.Variable
	(*RedirectParameters)(nil),              // 24: contester.proto.RedirectParameters
	(*ExecutionResultFlags)(nil),            // 25: contester.proto.ExecutionResultFlags
	(*ExecutionResultTime)(nil),             // 26: contester.proto.ExecutionResultTime
	(*Blob)(nil),                            // 27: contester.proto.Blob
}
var file_Local_proto_depIdxs = []int32{
	23, // 0: contester.proto.LocalEnvironment.variable:type_name -> contester.proto.LocalEnvironment.Variable
	1,  // 1: contester.proto.LocalExecutionParameters.environment:type_name -> contester.proto.LocalEnvironment
	24, // 2: contester.proto.LocalExecutionParameters.std_in:type_name -> contester.proto.RedirectParameters
	24, // 3: contester.proto.LocalExecutionParameters.std_out:type_name -> contester.proto.RedirectParameters
	24, // 4: contester.proto.LocalExecutionParameters.std_err:type_name -> contester.proto.RedirectParameters
	2,  // 5: contester.proto.LocalExecuteConnected.first:type_name -> contester.proto.LocalExecutionParameters
	2,  // 6: contester.proto.LocalExecuteConnected.second:type_name -> contester.proto.LocalExecutionParameters
	25, // 7: contester.proto.LocalExecutionResult.flags:type_name -> contester.proto.ExecutionResultFlags
	26, // 8: contester.proto.LocalExecutionResult.time:type_name -> contester.proto.ExecutionResultTime
	27, // 9: contester.proto.LocalExecutionResult.std_out:type_name -> contester.proto.Blob
	27, // 10: contester.proto.LocalExecutionResult.std_err:type_name -> contester.proto.Blob
	4,  // 11: contester.proto.LocalExecuteConnectedResult.first:type_name -> contester.proto.LocalExecutionResult
	4,  // 12: contester.proto.LocalExecuteConnectedResult.second:type_name -> contester.proto.LocalExecutionResult
	2,  // 13: contester.proto.LocalExecution.parameters:type_name -> contester.proto.LocalExecutionParameters
	4,  // 14: contester.proto.LocalExecution.result:type_name -> contester.proto.LocalExecutionResult
	0,  // 15: contester.proto.BinaryTypeResponse.result:type_name -> contester.proto.BinaryTypeResponse.Win32BinaryType
	11, // 16: contester.proto.IdentifyResponse.sandboxes:type_name -> contester.proto.SandboxLocations
	1,  // 17: contester.proto.IdentifyResponse.environment:type_name -> contester.proto.LocalEnvironment
	13, // 18: contester.proto.FileStats.entries:type_name -> contester.proto.FileStat
	18, // 19: contester.proto.CopyOperations.entries:type_name -> contester.proto.CopyOperation
	20, // 20: contester.proto.RepeatedNamePairEntries.entries:type_name -> contester.proto.NamePair
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_Local_proto_init() }
func file_Local_proto_init() {
	if File_Local_proto != nil {
		return
	}
	file_Blobs_proto_init()
	file_Execution_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Local_proto_rawDesc), len(file_Local_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Local_proto_goTypes,
		DependencyIndexes: file_Local_proto_depIdxs,
		EnumInfos:         file_Local_proto_enumTypes,
		MessageInfos:      file_Local_proto_msgTypes,
	}.Build()
	File_Local_proto = out.File
	file_Local_proto_goTypes = nil
	file_Local_proto_depIdxs = nil
}
