// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.6
// source: Local.proto

package contester_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryTypeResponse_Win32BinaryType int32

const (
	BinaryTypeResponse_SCS_32BIT_BINARY BinaryTypeResponse_Win32BinaryType = 0
	BinaryTypeResponse_SCS_DOS_BINARY   BinaryTypeResponse_Win32BinaryType = 1
	BinaryTypeResponse_SCS_WOW_BINARY   BinaryTypeResponse_Win32BinaryType = 2
	BinaryTypeResponse_SCS_PIF_BINARY   BinaryTypeResponse_Win32BinaryType = 3
	BinaryTypeResponse_SCS_POSIX_BINARY BinaryTypeResponse_Win32BinaryType = 4
	BinaryTypeResponse_SCS_OS216_BINARY BinaryTypeResponse_Win32BinaryType = 5
	BinaryTypeResponse_SCS_64BIT_BINARY BinaryTypeResponse_Win32BinaryType = 6
)

// Enum value maps for BinaryTypeResponse_Win32BinaryType.
var (
	BinaryTypeResponse_Win32BinaryType_name = map[int32]string{
		0: "SCS_32BIT_BINARY",
		1: "SCS_DOS_BINARY",
		2: "SCS_WOW_BINARY",
		3: "SCS_PIF_BINARY",
		4: "SCS_POSIX_BINARY",
		5: "SCS_OS216_BINARY",
		6: "SCS_64BIT_BINARY",
	}
	BinaryTypeResponse_Win32BinaryType_value = map[string]int32{
		"SCS_32BIT_BINARY": 0,
		"SCS_DOS_BINARY":   1,
		"SCS_WOW_BINARY":   2,
		"SCS_PIF_BINARY":   3,
		"SCS_POSIX_BINARY": 4,
		"SCS_OS216_BINARY": 5,
		"SCS_64BIT_BINARY": 6,
	}
)

func (x BinaryTypeResponse_Win32BinaryType) Enum() *BinaryTypeResponse_Win32BinaryType {
	p := new(BinaryTypeResponse_Win32BinaryType)
	*p = x
	return p
}

func (x BinaryTypeResponse_Win32BinaryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryTypeResponse_Win32BinaryType) Descriptor() protoreflect.EnumDescriptor {
	return file_Local_proto_enumTypes[0].Descriptor()
}

func (BinaryTypeResponse_Win32BinaryType) Type() protoreflect.EnumType {
	return &file_Local_proto_enumTypes[0]
}

func (x BinaryTypeResponse_Win32BinaryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryTypeResponse_Win32BinaryType.Descriptor instead.
func (BinaryTypeResponse_Win32BinaryType) EnumDescriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{7, 0}
}

type LocalEnvironment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Empty    bool                         `protobuf:"varint,1,opt,name=empty,proto3" json:"empty,omitempty"`
	Variable []*LocalEnvironment_Variable `protobuf:"bytes,2,rep,name=variable,proto3" json:"variable,omitempty"`
}

func (x *LocalEnvironment) Reset() {
	*x = LocalEnvironment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalEnvironment) ProtoMessage() {}

func (x *LocalEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalEnvironment.ProtoReflect.Descriptor instead.
func (*LocalEnvironment) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{0}
}

func (x *LocalEnvironment) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *LocalEnvironment) GetVariable() []*LocalEnvironment_Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

type LocalExecutionParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationName       string              `protobuf:"bytes,1,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	CommandLine           string              `protobuf:"bytes,2,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	CurrentDirectory      string              `protobuf:"bytes,3,opt,name=current_directory,json=currentDirectory,proto3" json:"current_directory,omitempty"`
	TimeLimitMicros       uint64              `protobuf:"varint,4,opt,name=time_limit_micros,json=timeLimitMicros,proto3" json:"time_limit_micros,omitempty"`
	MemoryLimit           uint64              `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CheckIdleness         bool                `protobuf:"varint,6,opt,name=check_idleness,json=checkIdleness,proto3" json:"check_idleness,omitempty"`
	Environment           *LocalEnvironment   `protobuf:"bytes,7,opt,name=environment,proto3" json:"environment,omitempty"`
	RestrictUi            bool                `protobuf:"varint,8,opt,name=restrict_ui,json=restrictUi,proto3" json:"restrict_ui,omitempty"`
	NoJob                 bool                `protobuf:"varint,9,opt,name=no_job,json=noJob,proto3" json:"no_job,omitempty"`
	ProcessLimit          uint32              `protobuf:"varint,10,opt,name=process_limit,json=processLimit,proto3" json:"process_limit,omitempty"`
	KernelTimeLimitMicros uint64              `protobuf:"varint,19,opt,name=kernel_time_limit_micros,json=kernelTimeLimitMicros,proto3" json:"kernel_time_limit_micros,omitempty"`
	WallTimeLimitMicros   uint64              `protobuf:"varint,20,opt,name=wall_time_limit_micros,json=wallTimeLimitMicros,proto3" json:"wall_time_limit_micros,omitempty"`
	StdIn                 *RedirectParameters `protobuf:"bytes,12,opt,name=std_in,json=stdIn,proto3" json:"std_in,omitempty"`
	StdOut                *RedirectParameters `protobuf:"bytes,13,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	StdErr                *RedirectParameters `protobuf:"bytes,14,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	CommandLineParameters []string            `protobuf:"bytes,16,rep,name=command_line_parameters,json=commandLineParameters,proto3" json:"command_line_parameters,omitempty"`
	SandboxId             string              `protobuf:"bytes,17,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	JoinStdoutStderr      bool                `protobuf:"varint,18,opt,name=join_stdout_stderr,json=joinStdoutStderr,proto3" json:"join_stdout_stderr,omitempty"`
}

func (x *LocalExecutionParameters) Reset() {
	*x = LocalExecutionParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalExecutionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecutionParameters) ProtoMessage() {}

func (x *LocalExecutionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExecutionParameters.ProtoReflect.Descriptor instead.
func (*LocalExecutionParameters) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{1}
}

func (x *LocalExecutionParameters) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *LocalExecutionParameters) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *LocalExecutionParameters) GetCurrentDirectory() string {
	if x != nil {
		return x.CurrentDirectory
	}
	return ""
}

func (x *LocalExecutionParameters) GetTimeLimitMicros() uint64 {
	if x != nil {
		return x.TimeLimitMicros
	}
	return 0
}

func (x *LocalExecutionParameters) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *LocalExecutionParameters) GetCheckIdleness() bool {
	if x != nil {
		return x.CheckIdleness
	}
	return false
}

func (x *LocalExecutionParameters) GetEnvironment() *LocalEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *LocalExecutionParameters) GetRestrictUi() bool {
	if x != nil {
		return x.RestrictUi
	}
	return false
}

func (x *LocalExecutionParameters) GetNoJob() bool {
	if x != nil {
		return x.NoJob
	}
	return false
}

func (x *LocalExecutionParameters) GetProcessLimit() uint32 {
	if x != nil {
		return x.ProcessLimit
	}
	return 0
}

func (x *LocalExecutionParameters) GetKernelTimeLimitMicros() uint64 {
	if x != nil {
		return x.KernelTimeLimitMicros
	}
	return 0
}

func (x *LocalExecutionParameters) GetWallTimeLimitMicros() uint64 {
	if x != nil {
		return x.WallTimeLimitMicros
	}
	return 0
}

func (x *LocalExecutionParameters) GetStdIn() *RedirectParameters {
	if x != nil {
		return x.StdIn
	}
	return nil
}

func (x *LocalExecutionParameters) GetStdOut() *RedirectParameters {
	if x != nil {
		return x.StdOut
	}
	return nil
}

func (x *LocalExecutionParameters) GetStdErr() *RedirectParameters {
	if x != nil {
		return x.StdErr
	}
	return nil
}

func (x *LocalExecutionParameters) GetCommandLineParameters() []string {
	if x != nil {
		return x.CommandLineParameters
	}
	return nil
}

func (x *LocalExecutionParameters) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *LocalExecutionParameters) GetJoinStdoutStderr() bool {
	if x != nil {
		return x.JoinStdoutStderr
	}
	return false
}

type LocalExecuteConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  *LocalExecutionParameters `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Second *LocalExecutionParameters `protobuf:"bytes,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *LocalExecuteConnected) Reset() {
	*x = LocalExecuteConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalExecuteConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecuteConnected) ProtoMessage() {}

func (x *LocalExecuteConnected) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExecuteConnected.ProtoReflect.Descriptor instead.
func (*LocalExecuteConnected) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{2}
}

func (x *LocalExecuteConnected) GetFirst() *LocalExecutionParameters {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *LocalExecuteConnected) GetSecond() *LocalExecutionParameters {
	if x != nil {
		return x.Second
	}
	return nil
}

type LocalExecutionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags          *ExecutionResultFlags `protobuf:"bytes,1,opt,name=flags,proto3" json:"flags,omitempty"`
	Time           *ExecutionResultTime  `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Memory         uint64                `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	ReturnCode     uint32                `protobuf:"varint,4,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	StdOut         *Blob                 `protobuf:"bytes,5,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	StdErr         *Blob                 `protobuf:"bytes,6,opt,name=std_err,json=stdErr,proto3" json:"std_err,omitempty"`
	TotalProcesses uint64                `protobuf:"varint,7,opt,name=total_processes,json=totalProcesses,proto3" json:"total_processes,omitempty"`
	KillSignal     int32                 `protobuf:"varint,8,opt,name=kill_signal,json=killSignal,proto3" json:"kill_signal,omitempty"`
	StopSignal     int32                 `protobuf:"varint,9,opt,name=stop_signal,json=stopSignal,proto3" json:"stop_signal,omitempty"`
	Error          string                `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LocalExecutionResult) Reset() {
	*x = LocalExecutionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecutionResult) ProtoMessage() {}

func (x *LocalExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExecutionResult.ProtoReflect.Descriptor instead.
func (*LocalExecutionResult) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{3}
}

func (x *LocalExecutionResult) GetFlags() *ExecutionResultFlags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *LocalExecutionResult) GetTime() *ExecutionResultTime {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LocalExecutionResult) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *LocalExecutionResult) GetReturnCode() uint32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *LocalExecutionResult) GetStdOut() *Blob {
	if x != nil {
		return x.StdOut
	}
	return nil
}

func (x *LocalExecutionResult) GetStdErr() *Blob {
	if x != nil {
		return x.StdErr
	}
	return nil
}

func (x *LocalExecutionResult) GetTotalProcesses() uint64 {
	if x != nil {
		return x.TotalProcesses
	}
	return 0
}

func (x *LocalExecutionResult) GetKillSignal() int32 {
	if x != nil {
		return x.KillSignal
	}
	return 0
}

func (x *LocalExecutionResult) GetStopSignal() int32 {
	if x != nil {
		return x.StopSignal
	}
	return 0
}

func (x *LocalExecutionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LocalExecuteConnectedResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  *LocalExecutionResult `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Second *LocalExecutionResult `protobuf:"bytes,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *LocalExecuteConnectedResult) Reset() {
	*x = LocalExecuteConnectedResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalExecuteConnectedResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecuteConnectedResult) ProtoMessage() {}

func (x *LocalExecuteConnectedResult) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExecuteConnectedResult.ProtoReflect.Descriptor instead.
func (*LocalExecuteConnectedResult) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{4}
}

func (x *LocalExecuteConnectedResult) GetFirst() *LocalExecutionResult {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *LocalExecuteConnectedResult) GetSecond() *LocalExecutionResult {
	if x != nil {
		return x.Second
	}
	return nil
}

type LocalExecution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parameters *LocalExecutionParameters `protobuf:"bytes,1,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Result     *LocalExecutionResult     `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *LocalExecution) Reset() {
	*x = LocalExecution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalExecution) ProtoMessage() {}

func (x *LocalExecution) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalExecution.ProtoReflect.Descriptor instead.
func (*LocalExecution) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{5}
}

func (x *LocalExecution) GetParameters() *LocalExecutionParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *LocalExecution) GetResult() *LocalExecutionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type BinaryTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pathname string `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
}

func (x *BinaryTypeRequest) Reset() {
	*x = BinaryTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryTypeRequest) ProtoMessage() {}

func (x *BinaryTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryTypeRequest.ProtoReflect.Descriptor instead.
func (*BinaryTypeRequest) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{6}
}

func (x *BinaryTypeRequest) GetPathname() string {
	if x != nil {
		return x.Pathname
	}
	return ""
}

type BinaryTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Failure bool                               `protobuf:"varint,1,opt,name=failure,proto3" json:"failure,omitempty"`
	Result  BinaryTypeResponse_Win32BinaryType `protobuf:"varint,2,opt,name=result,proto3,enum=contester.proto.BinaryTypeResponse_Win32BinaryType" json:"result,omitempty"`
}

func (x *BinaryTypeResponse) Reset() {
	*x = BinaryTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryTypeResponse) ProtoMessage() {}

func (x *BinaryTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryTypeResponse.ProtoReflect.Descriptor instead.
func (*BinaryTypeResponse) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{7}
}

func (x *BinaryTypeResponse) GetFailure() bool {
	if x != nil {
		return x.Failure
	}
	return false
}

func (x *BinaryTypeResponse) GetResult() BinaryTypeResponse_Win32BinaryType {
	if x != nil {
		return x.Result
	}
	return BinaryTypeResponse_SCS_32BIT_BINARY
}

type ClearSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sandbox string `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
}

func (x *ClearSandboxRequest) Reset() {
	*x = ClearSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearSandboxRequest) ProtoMessage() {}

func (x *ClearSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearSandboxRequest.ProtoReflect.Descriptor instead.
func (*ClearSandboxRequest) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{8}
}

func (x *ClearSandboxRequest) GetSandbox() string {
	if x != nil {
		return x.Sandbox
	}
	return ""
}

type IdentifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContesterId string `protobuf:"bytes,1,opt,name=contester_id,json=contesterId,proto3" json:"contester_id,omitempty"`
}

func (x *IdentifyRequest) Reset() {
	*x = IdentifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyRequest) ProtoMessage() {}

func (x *IdentifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyRequest.ProtoReflect.Descriptor instead.
func (*IdentifyRequest) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{9}
}

func (x *IdentifyRequest) GetContesterId() string {
	if x != nil {
		return x.ContesterId
	}
	return ""
}

type SandboxLocations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Compile string `protobuf:"bytes,1,opt,name=compile,proto3" json:"compile,omitempty"`
	Run     string `protobuf:"bytes,2,opt,name=run,proto3" json:"run,omitempty"`
}

func (x *SandboxLocations) Reset() {
	*x = SandboxLocations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxLocations) ProtoMessage() {}

func (x *SandboxLocations) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxLocations.ProtoReflect.Descriptor instead.
func (*SandboxLocations) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{10}
}

func (x *SandboxLocations) GetCompile() string {
	if x != nil {
		return x.Compile
	}
	return ""
}

func (x *SandboxLocations) GetRun() string {
	if x != nil {
		return x.Run
	}
	return ""
}

type IdentifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvokerId     string              `protobuf:"bytes,1,opt,name=invoker_id,json=invokerId,proto3" json:"invoker_id,omitempty"`
	Sandboxes     []*SandboxLocations `protobuf:"bytes,2,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	Environment   *LocalEnvironment   `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Platform      string              `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	PathSeparator string              `protobuf:"bytes,5,opt,name=path_separator,json=pathSeparator,proto3" json:"path_separator,omitempty"`
	Disks         []string            `protobuf:"bytes,6,rep,name=disks,proto3" json:"disks,omitempty"`
	ProgramFiles  []string            `protobuf:"bytes,7,rep,name=programFiles,proto3" json:"programFiles,omitempty"`
}

func (x *IdentifyResponse) Reset() {
	*x = IdentifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifyResponse) ProtoMessage() {}

func (x *IdentifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifyResponse.ProtoReflect.Descriptor instead.
func (*IdentifyResponse) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{11}
}

func (x *IdentifyResponse) GetInvokerId() string {
	if x != nil {
		return x.InvokerId
	}
	return ""
}

func (x *IdentifyResponse) GetSandboxes() []*SandboxLocations {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *IdentifyResponse) GetEnvironment() *LocalEnvironment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *IdentifyResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *IdentifyResponse) GetPathSeparator() string {
	if x != nil {
		return x.PathSeparator
	}
	return ""
}

func (x *IdentifyResponse) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *IdentifyResponse) GetProgramFiles() []string {
	if x != nil {
		return x.ProgramFiles
	}
	return nil
}

type FileStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDirectory bool   `protobuf:"varint,2,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	Size        uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Checksum    string `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *FileStat) Reset() {
	*x = FileStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat) ProtoMessage() {}

func (x *FileStat) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat.ProtoReflect.Descriptor instead.
func (*FileStat) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{12}
}

func (x *FileStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileStat) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *FileStat) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStat) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	SandboxId         string   `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	Expand            bool     `protobuf:"varint,3,opt,name=expand,proto3" json:"expand,omitempty"`
	CalculateChecksum bool     `protobuf:"varint,4,opt,name=calculate_checksum,json=calculateChecksum,proto3" json:"calculate_checksum,omitempty"`
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{13}
}

func (x *StatRequest) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *StatRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StatRequest) GetExpand() bool {
	if x != nil {
		return x.Expand
	}
	return false
}

func (x *StatRequest) GetCalculateChecksum() bool {
	if x != nil {
		return x.CalculateChecksum
	}
	return false
}

type FileStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*FileStat `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *FileStats) Reset() {
	*x = FileStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStats) ProtoMessage() {}

func (x *FileStats) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStats.ProtoReflect.Descriptor instead.
func (*FileStats) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{14}
}

func (x *FileStats) GetEntries() []*FileStat {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{15}
}

func (x *GetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{16}
}

type CopyOperation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalFileName      string `protobuf:"bytes,1,opt,name=local_file_name,json=localFileName,proto3" json:"local_file_name,omitempty"`
	RemoteLocation     string `protobuf:"bytes,2,opt,name=remote_location,json=remoteLocation,proto3" json:"remote_location,omitempty"`
	Upload             bool   `protobuf:"varint,3,opt,name=upload,proto3" json:"upload,omitempty"`
	Checksum           string `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ModuleType         string `protobuf:"bytes,5,opt,name=module_type,json=moduleType,proto3" json:"module_type,omitempty"`
	AuthorizationToken string `protobuf:"bytes,6,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
}

func (x *CopyOperation) Reset() {
	*x = CopyOperation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOperation) ProtoMessage() {}

func (x *CopyOperation) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOperation.ProtoReflect.Descriptor instead.
func (*CopyOperation) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{17}
}

func (x *CopyOperation) GetLocalFileName() string {
	if x != nil {
		return x.LocalFileName
	}
	return ""
}

func (x *CopyOperation) GetRemoteLocation() string {
	if x != nil {
		return x.RemoteLocation
	}
	return ""
}

func (x *CopyOperation) GetUpload() bool {
	if x != nil {
		return x.Upload
	}
	return false
}

func (x *CopyOperation) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *CopyOperation) GetModuleType() string {
	if x != nil {
		return x.ModuleType
	}
	return ""
}

func (x *CopyOperation) GetAuthorizationToken() string {
	if x != nil {
		return x.AuthorizationToken
	}
	return ""
}

type CopyOperations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries   []*CopyOperation `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	SandboxId string           `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
}

func (x *CopyOperations) Reset() {
	*x = CopyOperations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyOperations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOperations) ProtoMessage() {}

func (x *CopyOperations) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOperations.ProtoReflect.Descriptor instead.
func (*CopyOperations) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{18}
}

func (x *CopyOperations) GetEntries() []*CopyOperation {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CopyOperations) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type NamePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *NamePair) Reset() {
	*x = NamePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamePair) ProtoMessage() {}

func (x *NamePair) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamePair.ProtoReflect.Descriptor instead.
func (*NamePair) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{19}
}

func (x *NamePair) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NamePair) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type RepeatedNamePairEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries   []*NamePair `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	SandboxId string      `protobuf:"bytes,2,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
}

func (x *RepeatedNamePairEntries) Reset() {
	*x = RepeatedNamePairEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedNamePairEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedNamePairEntries) ProtoMessage() {}

func (x *RepeatedNamePairEntries) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedNamePairEntries.ProtoReflect.Descriptor instead.
func (*RepeatedNamePairEntries) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{20}
}

func (x *RepeatedNamePairEntries) GetEntries() []*NamePair {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RepeatedNamePairEntries) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

type RepeatedStringEntries struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []string `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *RepeatedStringEntries) Reset() {
	*x = RepeatedStringEntries{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatedStringEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedStringEntries) ProtoMessage() {}

func (x *RepeatedStringEntries) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedStringEntries.ProtoReflect.Descriptor instead.
func (*RepeatedStringEntries) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{21}
}

func (x *RepeatedStringEntries) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LocalEnvironment_Variable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expand bool   `protobuf:"varint,3,opt,name=expand,proto3" json:"expand,omitempty"`
}

func (x *LocalEnvironment_Variable) Reset() {
	*x = LocalEnvironment_Variable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Local_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalEnvironment_Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalEnvironment_Variable) ProtoMessage() {}

func (x *LocalEnvironment_Variable) ProtoReflect() protoreflect.Message {
	mi := &file_Local_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalEnvironment_Variable.ProtoReflect.Descriptor instead.
func (*LocalEnvironment_Variable) Descriptor() ([]byte, []int) {
	return file_Local_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LocalEnvironment_Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalEnvironment_Variable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LocalEnvironment_Variable) GetExpand() bool {
	if x != nil {
		return x.Expand
	}
	return false
}

var File_Local_proto protoreflect.FileDescriptor

var file_Local_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b,
	0x42, 0x6c, 0x6f, 0x62, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a,
	0x10, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x46, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61,
	0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x1a,
	0x4c, 0x0a, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x22, 0xd8, 0x06,
	0x0a, 0x18, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64,
	0x6c, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x64, 0x6c, 0x65, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x43, 0x0a, 0x0b, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x5f, 0x75, 0x69, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x55,
	0x69, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x6f, 0x5f, 0x6a, 0x6f, 0x62, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x6e, 0x6f, 0x4a, 0x6f, 0x62, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x37, 0x0a,
	0x18, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x18, 0x13, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x15, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x33, 0x0a, 0x16, 0x77, 0x61, 0x6c, 0x6c, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x5f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x18, 0x14, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x77, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x73,
	0x74, 0x64, 0x5f, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x52, 0x05, 0x73, 0x74, 0x64, 0x49, 0x6e, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x74, 0x64, 0x5f, 0x6f,
	0x75, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x3c, 0x0a, 0x07, 0x73, 0x74, 0x64, 0x5f, 0x65, 0x72, 0x72,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x06, 0x73, 0x74, 0x64,
	0x45, 0x72, 0x72, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x10,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x6e,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6a, 0x6f,
	0x69, 0x6e, 0x5f, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x18, 0x12, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x53, 0x74, 0x64, 0x6f,
	0x75, 0x74, 0x53, 0x74, 0x64, 0x65, 0x72, 0x72, 0x22, 0x9b, 0x01, 0x0a, 0x15, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x3f, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x05, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x06,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0xa7, 0x03, 0x0a, 0x14, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x3b, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x38, 0x0a, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x2e, 0x0a, 0x07, 0x73, 0x74, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x06, 0x73, 0x74, 0x64, 0x4f, 0x75, 0x74, 0x12,
	0x2e, 0x0a, 0x07, 0x73, 0x74, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x06, 0x73, 0x74, 0x64, 0x45, 0x72, 0x72, 0x12,
	0x27, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x69, 0x6c, 0x6c,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6b,
	0x69, 0x6c, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f,
	0x70, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x73, 0x74, 0x6f, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x99, 0x01, 0x0a, 0x1b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x3b, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x3d, 0x0a,
	0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x9a, 0x01, 0x0a,
	0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x49, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x3d, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2f, 0x0a, 0x11, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x74, 0x68, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x74, 0x68, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa3, 0x02, 0x0a, 0x12, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x57, 0x69, 0x6e, 0x33, 0x32, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x57, 0x69, 0x6e,
	0x33, 0x32, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x53, 0x43, 0x53, 0x5f, 0x33, 0x32, 0x42, 0x49, 0x54, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43, 0x53, 0x5f, 0x44, 0x4f, 0x53, 0x5f, 0x42, 0x49,
	0x4e, 0x41, 0x52, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43, 0x53, 0x5f, 0x57, 0x4f,
	0x57, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x43,
	0x53, 0x5f, 0x50, 0x49, 0x46, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x03, 0x12, 0x14,
	0x0a, 0x10, 0x53, 0x43, 0x53, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x58, 0x5f, 0x42, 0x49, 0x4e, 0x41,
	0x52, 0x59, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x43, 0x53, 0x5f, 0x4f, 0x53, 0x32, 0x31,
	0x36, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x43,
	0x53, 0x5f, 0x36, 0x34, 0x42, 0x49, 0x54, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x06,
	0x22, 0x2f, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x22, 0x34, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x53, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x70, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x75, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x22, 0xb4, 0x02, 0x0a, 0x10, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x09, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0b,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x74, 0x68, 0x53, 0x65, 0x70, 0x61, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x71,
	0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x22, 0x87, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62,
	0x6f, 0x78, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x12, 0x2d, 0x0a, 0x12,
	0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x22, 0x40, 0x0a, 0x09, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x20, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0xe6, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x70, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x69, 0x0a, 0x0e, 0x43, 0x6f, 0x70, 0x79,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x38, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x70, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x08, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6d, 0x0a, 0x17, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x69, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x52, 0x65, 0x70, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x4b, 0x0a, 0x1c, 0x6f,
	0x72, 0x67, 0x2e, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x72, 0x61, 0x79, 0x2e, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x2b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x2f, 0x72, 0x75, 0x6e, 0x6c, 0x69, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Local_proto_rawDescOnce sync.Once
	file_Local_proto_rawDescData = file_Local_proto_rawDesc
)

func file_Local_proto_rawDescGZIP() []byte {
	file_Local_proto_rawDescOnce.Do(func() {
		file_Local_proto_rawDescData = protoimpl.X.CompressGZIP(file_Local_proto_rawDescData)
	})
	return file_Local_proto_rawDescData
}

var file_Local_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Local_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_Local_proto_goTypes = []interface{}{
	(BinaryTypeResponse_Win32BinaryType)(0), // 0: contester.proto.BinaryTypeResponse.Win32BinaryType
	(*LocalEnvironment)(nil),                // 1: contester.proto.LocalEnvironment
	(*LocalExecutionParameters)(nil),        // 2: contester.proto.LocalExecutionParameters
	(*LocalExecuteConnected)(nil),           // 3: contester.proto.LocalExecuteConnected
	(*LocalExecutionResult)(nil),            // 4: contester.proto.LocalExecutionResult
	(*LocalExecuteConnectedResult)(nil),     // 5: contester.proto.LocalExecuteConnectedResult
	(*LocalExecution)(nil),                  // 6: contester.proto.LocalExecution
	(*BinaryTypeRequest)(nil),               // 7: contester.proto.BinaryTypeRequest
	(*BinaryTypeResponse)(nil),              // 8: contester.proto.BinaryTypeResponse
	(*ClearSandboxRequest)(nil),             // 9: contester.proto.ClearSandboxRequest
	(*IdentifyRequest)(nil),                 // 10: contester.proto.IdentifyRequest
	(*SandboxLocations)(nil),                // 11: contester.proto.SandboxLocations
	(*IdentifyResponse)(nil),                // 12: contester.proto.IdentifyResponse
	(*FileStat)(nil),                        // 13: contester.proto.FileStat
	(*StatRequest)(nil),                     // 14: contester.proto.StatRequest
	(*FileStats)(nil),                       // 15: contester.proto.FileStats
	(*GetRequest)(nil),                      // 16: contester.proto.GetRequest
	(*EmptyMessage)(nil),                    // 17: contester.proto.EmptyMessage
	(*CopyOperation)(nil),                   // 18: contester.proto.CopyOperation
	(*CopyOperations)(nil),                  // 19: contester.proto.CopyOperations
	(*NamePair)(nil),                        // 20: contester.proto.NamePair
	(*RepeatedNamePairEntries)(nil),         // 21: contester.proto.RepeatedNamePairEntries
	(*RepeatedStringEntries)(nil),           // 22: contester.proto.RepeatedStringEntries
	(*LocalEnvironment_Variable)(nil),       // 23: contester.proto.LocalEnvironment.Variable
	(*RedirectParameters)(nil),              // 24: contester.proto.RedirectParameters
	(*ExecutionResultFlags)(nil),            // 25: contester.proto.ExecutionResultFlags
	(*ExecutionResultTime)(nil),             // 26: contester.proto.ExecutionResultTime
	(*Blob)(nil),                            // 27: contester.proto.Blob
}
var file_Local_proto_depIdxs = []int32{
	23, // 0: contester.proto.LocalEnvironment.variable:type_name -> contester.proto.LocalEnvironment.Variable
	1,  // 1: contester.proto.LocalExecutionParameters.environment:type_name -> contester.proto.LocalEnvironment
	24, // 2: contester.proto.LocalExecutionParameters.std_in:type_name -> contester.proto.RedirectParameters
	24, // 3: contester.proto.LocalExecutionParameters.std_out:type_name -> contester.proto.RedirectParameters
	24, // 4: contester.proto.LocalExecutionParameters.std_err:type_name -> contester.proto.RedirectParameters
	2,  // 5: contester.proto.LocalExecuteConnected.first:type_name -> contester.proto.LocalExecutionParameters
	2,  // 6: contester.proto.LocalExecuteConnected.second:type_name -> contester.proto.LocalExecutionParameters
	25, // 7: contester.proto.LocalExecutionResult.flags:type_name -> contester.proto.ExecutionResultFlags
	26, // 8: contester.proto.LocalExecutionResult.time:type_name -> contester.proto.ExecutionResultTime
	27, // 9: contester.proto.LocalExecutionResult.std_out:type_name -> contester.proto.Blob
	27, // 10: contester.proto.LocalExecutionResult.std_err:type_name -> contester.proto.Blob
	4,  // 11: contester.proto.LocalExecuteConnectedResult.first:type_name -> contester.proto.LocalExecutionResult
	4,  // 12: contester.proto.LocalExecuteConnectedResult.second:type_name -> contester.proto.LocalExecutionResult
	2,  // 13: contester.proto.LocalExecution.parameters:type_name -> contester.proto.LocalExecutionParameters
	4,  // 14: contester.proto.LocalExecution.result:type_name -> contester.proto.LocalExecutionResult
	0,  // 15: contester.proto.BinaryTypeResponse.result:type_name -> contester.proto.BinaryTypeResponse.Win32BinaryType
	11, // 16: contester.proto.IdentifyResponse.sandboxes:type_name -> contester.proto.SandboxLocations
	1,  // 17: contester.proto.IdentifyResponse.environment:type_name -> contester.proto.LocalEnvironment
	13, // 18: contester.proto.FileStats.entries:type_name -> contester.proto.FileStat
	18, // 19: contester.proto.CopyOperations.entries:type_name -> contester.proto.CopyOperation
	20, // 20: contester.proto.RepeatedNamePairEntries.entries:type_name -> contester.proto.NamePair
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_Local_proto_init() }
func file_Local_proto_init() {
	if File_Local_proto != nil {
		return
	}
	file_Blobs_proto_init()
	file_Execution_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Local_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalEnvironment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalExecutionParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalExecuteConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalExecutionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalExecuteConnectedResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalExecution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearSandboxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SandboxLocations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyOperation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyOperations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedNamePairEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatedStringEntries); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Local_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalEnvironment_Variable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Local_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Local_proto_goTypes,
		DependencyIndexes: file_Local_proto_depIdxs,
		EnumInfos:         file_Local_proto_enumTypes,
		MessageInfos:      file_Local_proto_msgTypes,
	}.Build()
	File_Local_proto = out.File
	file_Local_proto_rawDesc = nil
	file_Local_proto_goTypes = nil
	file_Local_proto_depIdxs = nil
}
