// Code generated by protoc-gen-go.
// source: rpcfour.proto
// DO NOT EDIT!

package rpc4

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Header_MessageType int32

const (
	Header_REQUEST  Header_MessageType = 1
	Header_RESPONSE Header_MessageType = 2
	Header_ERROR    Header_MessageType = 3
	Header_CANCEL   Header_MessageType = 4
)

var Header_MessageType_name = map[int32]string{
	1: "REQUEST",
	2: "RESPONSE",
	3: "ERROR",
	4: "CANCEL",
}
var Header_MessageType_value = map[string]int32{
	"REQUEST":  1,
	"RESPONSE": 2,
	"ERROR":    3,
	"CANCEL":   4,
}

func (x Header_MessageType) Enum() *Header_MessageType {
	p := new(Header_MessageType)
	*p = x
	return p
}
func (x Header_MessageType) String() string {
	return proto.EnumName(Header_MessageType_name, int32(x))
}
func (x Header_MessageType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Header_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Header_MessageType_value, data, "Header_MessageType")
	if err != nil {
		return err
	}
	*x = Header_MessageType(value)
	return nil
}

type Header struct {
	Sequence         *uint64             `protobuf:"varint,1,opt,name=sequence" json:"sequence,omitempty"`
	MessageType      *Header_MessageType `protobuf:"varint,2,opt,name=message_type,enum=rpc4.Header_MessageType" json:"message_type,omitempty"`
	PayloadPresent   *bool               `protobuf:"varint,3,opt,name=payload_present" json:"payload_present,omitempty"`
	Method           *string             `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}

func (m *Header) GetSequence() uint64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *Header) GetMessageType() Header_MessageType {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *Header) GetPayloadPresent() bool {
	if m != nil && m.PayloadPresent != nil {
		return *m.PayloadPresent
	}
	return false
}

func (m *Header) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func init() {
	proto.RegisterEnum("rpc4.Header_MessageType", Header_MessageType_name, Header_MessageType_value)
}
